project:
  type: website
  output-dir: docs


website:
  title: "Pathways taken after high school - Southwest"
  navbar:
    left:
      - href: index.qmd
        text: Summary
      - text: Data Prep and Summaries
        icon: fa-gear
        menu:
          - text: K12Enrollment
            href: k12enrollment.qmd
          - text: K12Orgs
            href: k12orgs.qmd
          - text: ACT
            href: act.qmd
          - text: AP
            href: ap.qmd
          - text: CTEEnrollment
            href: cteenrollment.qmd
          - text: CTEDemographics
            href: ctedemographics.qmd
          - text: Assessments
            href: assessments.qmd
          - text: SAT
            href: sat.qmd
          - text: National Student Clearinghouse - Enrollment
            href: nscenrollment.qmd
          - text: National Student Clearinghouse - Completions
            href: nsccompletions.qmd
          - text: Employment
            href: employment.qmd
          - text: Employment states each year
            href: emp_states_each_year.qmd
          - text: Unemployment
            href: unemployment.qmd
          - text: Average wages
            href: avgwages.qmd
      - text: Analysis
        icon: fa-gear
        menu:
          - text: Multiple Correspondence Analysis
            href: analysis_mca.qmd
          - text: Dependent Variable States
            href: analysis_dep_var_states.qmd
          - text: Local Employment Cross-tabs
            href: analysis_local_employment_ct.qmd
          - text: Post-secondary pathways cross-tabs
            href: analysis_post_secondary_pathways_ct.qmd
          - text: Multivariate Confirmation Analysis - Logistic Regression
            href: analysis_multivariate_confirmation_analysis.qmd
          - text: Non-college graduates
            href: analysis_non_post_secondary_graduates.qmd
          - text: Multivariate Confirmation Analysis on non-college grads - Logistic Regression
            href: analysis_multivariate_confirmation_non_college_grads.qmd
          - text: Further analysis on non-college grads
            href: analysis_non_college_deeper.qmd
      - text: One-page summaries of pathways
        icon: fa-gear
        menu:
          - text: Pathway - Anchored
            href: pathway_anchored.qmd
          - text: Pathway - Mobility
            href: pathway_mobility.qmd
          - text: Pathway - Unanchared / At-Risk
            href: pathway_unanchored.qmd
        


format:
  html:
    theme: cosmo
    toc: true