{
  "hash": "f0f62c12605e1444f2c365172dcc6e1e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Correspondence Analysis\"\neditor: visual\n---\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaster.original <- read.csv(\"Data/SLEDS/Masters/Master.csv\") %>%\n  drop_na(Dem_Desc)\n\nkable(names(master.original))\n```\n\n::: {.cell-output-display}\n\n\n|x                                                  |\n|:--------------------------------------------------|\n|PersonID                                           |\n|K12OrganizationID                                  |\n|OrganizationName                                   |\n|county.name                                        |\n|countyfp                                           |\n|Dem_Desc                                           |\n|edr                                                |\n|planning.region                                    |\n|grad.year                                          |\n|grad.year.covid                                    |\n|Gender                                             |\n|LimitedEnglishProficiencyIndicator                 |\n|HomelessIndicator                                  |\n|economic.status                                    |\n|pseo.participant                                   |\n|SpecialEdStatus                                    |\n|non.english.home                                   |\n|RaceEthnicity                                      |\n|n.years.attended                                   |\n|ACTCompositeScore                                  |\n|took.ACT                                           |\n|ap.exam                                            |\n|total.cte.courses.taken                            |\n|ACTE.SPED                                          |\n|Agriculture..Food..and.Natural.Resources           |\n|Architecture...Construction                        |\n|Arts..A.V.Technology...Communication               |\n|Business..Management...Administrative              |\n|Diversified                                        |\n|Education...Training                               |\n|Finance                                            |\n|Government...Public.Administration                 |\n|Health.Science                                     |\n|Hospitality...Tourism                              |\n|Human.Services                                     |\n|Information.Technology                             |\n|Law..Public.Safety...Security                      |\n|Manufacturing                                      |\n|Marketing                                          |\n|Program.Area..Diversified.                         |\n|Science..Technology..Engineering....Mathematics    |\n|STEM                                               |\n|Transportation..Distribution...Logistics           |\n|Work.Experience.Handicapped                        |\n|Work.Experience.Handicapped..16.20..on.IEP.        |\n|Work.Experience.Career.Exploration..age.14.15.on.I |\n|Work.Experience.Disadvantaged                      |\n|Youth.Apprenticeship                               |\n|cte.achievement                                    |\n|english.learner                                    |\n|MCA.M                                              |\n|MCA.R                                              |\n|MCA.S                                              |\n|sat.taken                                          |\n|attended.ps                                        |\n|first.attend.ps                                    |\n|attended.ps.first.year                             |\n|attended.ps.years.hsgrad                           |\n|attended.ps.within.first.year.hsgrad               |\n|n.institutions                                     |\n|first.InstitutionSector                            |\n|ps.sector.1                                        |\n|ps.sector.2                                        |\n|ps.sector.3                                        |\n|ps.sector.4                                        |\n|ps.sector.5                                        |\n|ps.sector.6                                        |\n|ps.sector.7                                        |\n|ps.sector.8                                        |\n|ps.sector.9                                        |\n|ps.in.same.ruca                                    |\n|ps.in.same.edr                                     |\n|ps.in.same.pr                                      |\n|ps.in.MN                                           |\n|hs.grad.year                                       |\n|ps.attended.in.same.ruca                           |\n|ps.attended.in.same.edr                            |\n|ps.attended.in.same.pr                             |\n|ps.attended.in.MN                                  |\n|ps.grad                                            |\n|min.ps.grad.year                                   |\n|max.ps.grad.year                                   |\n|years.between.grads                                |\n|ps.grad.InstitutionSector                          |\n|highest.cred.level                                 |\n|ps.grad.in.same.ruca                               |\n|ps.grad.in.same.edr                                |\n|ps.grad.in.same.pr                                 |\n|ps.grad.in.MN                                      |\n|mn.emp.record.hs.grad.year                         |\n|mn.emp.record.hs.grad.year.2                       |\n|mn.emp.record.hs.grad.year.7                       |\n|meaningful.emp.hs.grad.year                        |\n|meaningful.emp.hs.grad.year.2                      |\n|meaningful.emp.hs.grad.year.7                      |\n|hs.grad.year.county.match                          |\n|hs.grad.year.2.county.match                        |\n|hs.grad.year.7.county.match                        |\n|hs.grad.year.edr.match                             |\n|hs.grad.year.2.edr.match                           |\n|hs.grad.year.7.edr.match                           |\n|hs.grad.year.region.match                          |\n|hs.grad.year.2.region.match                        |\n|hs.grad.year.7.region.match                        |\n|hs.grad.year.state.match                           |\n|hs.grad.year.2.state.match                         |\n|hs.grad.year.7.state.match                         |\n|ind.match.hs.grad.year                             |\n|ind.match.hs.grad.year.2                           |\n|ind.match.hs.grad.year.7                           |\n|avg.unemp.rate                                     |\n|wages.3year.avg                                    |\n|avg.wages.pct.state                                |\n|ps.grad.location                                   |\n\n\n:::\n:::\n\n\n<br>\n\nThe purpose of multiple correspondence analysis is to examine any patterns among the independent variables with the goal of eliminating variables that are redundant - essentially two variables that are explaining the same thing. This type of analysis is not meant to confirm any predictions, but rather explore the data and make decisions on what data should be included in the prediction model.\n\n<br>\n\n# Independent variables\n\nThe master dataset is composed of 50,830 rows. Each row represents an individual that graduated (StatusEnd = 8 or 9) from a high school located in the Northeasy region (defined by project) between 2008 and 2023.\n\nThe master dataset is also composed of 114 columns. Columns mainly represent various socio-economic, demographic, and educational career characteristics of the individual as well as a few characteristics of the high school geographic from which they graduated (i.e. county unemployment). The variables for each individual is composed of a mix of categorical and numerical values. In this analysis, we will only be exploring categorical data.\n\nHere is a list of all the categorical variables we will be examining in this analysis along with a description of each.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqual.var.names <-  c(\"PersonID\", \"hs.grad.year\", \"Gender\", \"grad.year.covid\", \"LimitedEnglishProficiencyIndicator\", \"HomelessIndicator\", \"economic.status\", \"pseo.participant\", \"SpecialEdStatus\", \"non.english.home\", \"RaceEthnicity\", \"Dem_Desc\", \"edr\", \"took.ACT\", \"ap.exam\", \"cte.achievement\", \"english.learner\", \"sat.taken\", \"attended.ps.within.first.year.hsgrad\", \"attended.ps\", \"ps.grad\", \"ps.grad.InstitutionSector\", \"highest.cred.level\", \"ps.grad.location\")\n\nquan.var.names <- c(\"total.cte.courses.taken\", \"cte.0\", \"cte.1\", \"cte.2\", \"cte.3\", \"cte.4\", \"cte.5\", \"cte.6\", \"cte.7\", \"cte.8\", \"cte.9\", \"cte.10\", \"cte.11\", \"cte.12\", \"cte.14\", \"cte.21\", \"cte.22\", \"cte.23\", \"cte.24\", \"cte.25\", \"cte.26\", \"avg.cte.intensity\", \"MCA.M\", \"MCA.R\", \"MCA.S\", \"avg.unemp.rate\", \"wages.3year.avg\", \"avg.wages.pct.state\")\n\nindependent.var.names <- c(\"hs.grad.year\", \"Gender\", \"LimitedEnglishProficiencyIndicator\", \"HomelessIndicator\", \"economic.status\", \"pseo.participant\", \"SpecialEdStatus\", \"non.english.home\", \"RaceEthnicity\", \"Dem_Desc\", \"edr\", \"took.ACT\", \"ap.exam\", \"total.cte.courses.taken\", \"cte.achievement\", \"avg.cte.intensity\", \"MCA.M\", \"MCA.R\", \"MCA.S\", \"sat.taken\", \"attended.ps\", \"ps.grad\", \"highest.cred.level\", \"ps.grad.location\", \"avg.unemp.rate\", \"wages.3year.avg\")\n\ncte.cc.var.names <- c(\"cte.1\", \"cte.2\", \"cte.3\", \"cte.4\", \"cte.5\", \"cte.6\", \"cte.7\", \"cte.8\", \"cte.9\", \"cte.10\", \"cte.11\", \"cte.12\", \"cte.14\", \"cte.21\", \"cte.22\", \"cte.23\", \"cte.24\", \"cte.25\")\n\nind.qual.var <- master.original %>%\n  select(all_of(`qual.var.names`)) %>%\n  mutate_at(2:ncol(.), as.factor)\n```\n:::\n\n\n<br>\n\n- **Demographics**\n  - *`grad.year`:* this is the year they graduated high school.\n  - `grad.year.covid`: this is a value representing whether the individual graduated high school before 2020 or after 2021.\n    - Pre-covid grad\n    - Post-covid grad\n  - *`Gender`:*\n    - M = male\n    - F = female\n  - *`RaceEthnicity`:*\n    - AI = American Indian\n    - Asian/PI = Asian or Pacific Islander\n    - Black = African American\n    - Hispanic = any race any Hispanic or Latino\n    - Unknown = unknown race or ethnicity\n    - White = Caucasian and not Hispanic\n  - *`LimitedEnglishProficiencyIndicator`:*\n    - Y = identified as having limited English proficiency at some point between 10th and 12th grade, otherwise N.\n  - *`HomelessIndicator`:*\n    - Y = the individual was identified as homeless at any point between 10th and 12th grade, otherwise N.\n  - *`economic.status`:*\n    - 1 = the individual was eligible for free or reduced lunch (codes 1,2,4,5) at any point between 10th and 12th grade, otherwise 0.\n  - *`SpecialEdStatus`:*\n    - 1 = the individual required special education services at some point between 10th and 12th grade, otherwise 0.\n  - *`non.english.home`:*\n    - 1 = the individual was identified as having English as not the primary language spoken at home between 10th and 12th grad, otherwise 0.\n  - *`english.learner`:*\n    - 1 = the individual was identified as an \"English learner\" at least one time between 10th and 12th grade, otherwise 0.\n\n<br>\n\n- **High school characteristics**\n  - *`Dem_Desc`:* the RUCA category of the high school from which the individual graduated.\n\n<br>\n\n- **High school accomplishments**\n  - *`pseo.participant`:*\n    - 1 = the individual participated in a PSEO course sometime between 10th and 12th grade, otherwise 0. There are also NA values in this due to missing data.\n  - *`took.ACT:`* whether an individual took the ACT exam\n    - Yes\n    - No\n  - *`ap.exam`:*\n    - 1 = the individual took an AP exam at some point,\n    - 0 = the individual did not take an AP exam.\n  - *`cte.achievement`:* three indicators with\n    - \"CTE concentrator or completor\" = self-explanatory,\n    - \"CTE participant\" = they took a CTE course but was not a concentrator or completor, and,\n    - \"No CTE\" = they didn't take a CTE course\n  - *`sat.taken`:*\n    - 1 = individual took the SAT at some point between 10th and 12th grade, otherwise 0.\n\n<br>\n\n- **Post-secondary**\n  - *`attended.ps.within.first.year.hsgrad`:* the individual attended a post-secondary institution within the first year of graduating high school.\n    - Yes = Attended PS within first year\n    - No = Attended PS but not within first year\n    - NA = never attended PS or attended but only to withdraw.\n  - *`attended.ps`:*\n    - Yes = the individual attended a post-secondary education institution.\n    - No = never attended post-secondary, or attended but only \"W\" or \"D\".\n  - *`ps.grad`:*\n    - Yes = Graduated from a post-secondary institution by 2023\n    - Attending ps = attending a post-secondary institution as of 2023\n    - No = Not attending a post-secondary institution nor graduated from one as of 2023.\n  - *`ps.grad.InstitutionSector`:* the institution sector of the post-secondary school from which an individual has graduated.\n    - 1 - Public, 4-year or above\n    - 2 - Private not-for-profit, 4-year or above\n    - 3 - Private for-profit, 4-year or above\n    - 4 - Public, 2-year\n    - 5 - Private not-for-profit, 2-year\n    - 6 - Private for-profit, 2-year\n    - 7 - Public, less-than 2-year\n    - 8 - Private not-for-profit, less-than 2-year\n    - 9 - Private for-profit, less-than 2-year\n    - 10 - multiple sectors (if attended multiple institutions)\n    - 99 - Sector unknown (not active)\n    - \"Never attended ps\" = the individual never attended a post-secondary institution\n    - \"Did not grad\" = the individual attended a post-secondary institution but did not graduate.\n  - *`highest.cred.level`:* an identifier of the highest credential earned by the PersonID. The categories are;\n    - Did not graduate ps\n    - Attending ps\n    - Less than associate degree\n    - Associate degree\n    - Bachelors degree\n    - Higher than bachelors degree.\n  - `ps.grad.location`: this is the following;\n    - ps.grad.region: graduated from a college in the same region as their high school, but not same EDR\n    - ps.grad.MN: graduated from a college in MN but not same region or EDR\n    - ps.grad.outside: graduated from a college outside MN, but not in region or EDR or Minnesota\n    - Did not grad: attended but did not graduate college or attended but did not graduate\n    - Attending ps: Currently attending post-secondary at grad.year.x\n\n<br>\n\n# Frequencies\n\nFirst, lets check to see there aren't any variable categories with very low frequencies (less than 2%) which can distort the analysis.\n\nThe tables below shows there are a few to be concerned about.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nind.qual.freq <- ind.qual.var %>%\n  gather(key = \"key\", value = \"value\", 2:ncol(.)) %>%\n  group_by(key, value) %>%\n  summarize(n = n()) %>%\n  ungroup() %>%\n  mutate(pct = n / nrow(master.original)) %>%\n  mutate(data_id = seq(n()))\n\nind.qual.freq.plot <- ggplot(ind.qual.freq, aes(value, n)) +\n  facet_wrap(~key, ncol = 4, scales = \"free\") +\n  geom_col_interactive(position = \"dodge\", aes(data_id = data_id, tooltip = paste(key, \"\\n\", value, \"\\nN = \", comma(n, accuracy = 1), \"\\nPercent: \", percent(pct, accuracy = .1), sep = \"\"))) +\n  labs(x=\"\", y = \"\", color=\"\", title = \"N for each independent, categorical variable\")+\n  scale_y_continuous(labels=scales::comma)+\n  theme_bar+\n  scale_fill_manual(values = brewer.pal(n = 5, \"RdYlBu\"),\n                    guide = guide_legend(ncol = 3)) +\n  theme(legend.position = \"bottom\",\n        text = element_text(size = 14),\n        axis.text.x = element_text(angle = 25, hjust = .9))\n\n\ngirafe(ggobj = ind.qual.freq.plot, width_svg = 10, height_svg = 20) %>%\n  girafe_options(opts_selection(type = \"none\"),\n                 opts_sizing(rescale = FALSE))      \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-c865fdb7e62bb59be741\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c865fdb7e62bb59be741\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_39808f443929a61b' viewBox='0 0 720 1440'>\\n <defs id='svg_39808f443929a61b_defs'>\\n  <clipPath id='svg_39808f443929a61b_c1'>\\n   <rect x='0' y='0' width='720' height='1440'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c2'>\\n   <rect x='57.59' y='45.66' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c3'>\\n   <rect x='57.59' y='301.69' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c4'>\\n   <rect x='57.59' y='560.53' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c5'>\\n   <rect x='57.59' y='808' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c6'>\\n   <rect x='57.59' y='1021.46' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c7'>\\n   <rect x='57.59' y='1250.7' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c8'>\\n   <rect x='232.3' y='45.66' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c9'>\\n   <rect x='232.3' y='301.69' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c10'>\\n   <rect x='232.3' y='560.53' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c11'>\\n   <rect x='232.3' y='808' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c12'>\\n   <rect x='232.3' y='1021.46' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c13'>\\n   <rect x='232.3' y='1250.7' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c14'>\\n   <rect x='407' y='45.66' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c15'>\\n   <rect x='407' y='301.69' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c16'>\\n   <rect x='407' y='560.53' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c17'>\\n   <rect x='407' y='808' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c18'>\\n   <rect x='407' y='1021.46' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c19'>\\n   <rect x='407' y='1250.7' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c20'>\\n   <rect x='581.7' y='45.66' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c21'>\\n   <rect x='581.7' y='301.69' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c22'>\\n   <rect x='581.7' y='560.53' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c23'>\\n   <rect x='581.7' y='808' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c24'>\\n   <rect x='581.7' y='1021.46' width='132.82' height='148.37'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c25'>\\n   <rect x='57.59' y='1231.57' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c26'>\\n   <rect x='232.3' y='1231.57' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c27'>\\n   <rect x='407' y='1231.57' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c28'>\\n   <rect x='57.59' y='1002.33' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c29'>\\n   <rect x='232.3' y='1002.33' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c30'>\\n   <rect x='407' y='1002.33' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c31'>\\n   <rect x='581.7' y='1002.33' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c32'>\\n   <rect x='57.59' y='788.86' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c33'>\\n   <rect x='232.3' y='788.86' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c34'>\\n   <rect x='407' y='788.86' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c35'>\\n   <rect x='581.7' y='788.86' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c36'>\\n   <rect x='57.59' y='541.4' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c37'>\\n   <rect x='232.3' y='541.4' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c38'>\\n   <rect x='407' y='541.4' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c39'>\\n   <rect x='581.7' y='541.4' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c40'>\\n   <rect x='57.59' y='282.56' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c41'>\\n   <rect x='232.3' y='282.56' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c42'>\\n   <rect x='407' y='282.56' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c43'>\\n   <rect x='581.7' y='282.56' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c44'>\\n   <rect x='57.59' y='26.53' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c45'>\\n   <rect x='232.3' y='26.53' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c46'>\\n   <rect x='407' y='26.53' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_39808f443929a61b_c47'>\\n   <rect x='581.7' y='26.53' width='132.82' height='19.14'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_39808f443929a61b_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_39808f443929a61b_c1)'>\\n   <rect x='0' y='0' width='720' height='1440' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n   <rect x='0' y='0' width='720' height='1440' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c2)'>\\n   <rect x='57.59' y='45.66' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='57.59,187.29 190.41,187.29' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,155.95 190.41,155.95' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,124.62 190.41,124.62' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,93.28 190.41,93.28' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,61.95 190.41,61.95' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='93.82,194.03 93.82,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='154.19,194.03 154.19,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e1' x='66.65' y='52.4' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='18' title='ap.exam&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 43,045&amp;lt;br/&amp;gt;Percent: 84.7%'/>\\n   <rect id='svg_39808f443929a61b_e2' x='127.02' y='162.89' width='54.33' height='24.39' fill='#595959' fill-opacity='1' stroke='none' data-id='19' title='ap.exam&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 7,785&amp;lt;br/&amp;gt;Percent: 15.3%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c3)'>\\n   <rect x='57.59' y='301.69' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='57.59,443.32 190.41,443.32' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,405.79 190.41,405.79' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,368.26 190.41,368.26' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,330.73 190.41,330.73' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='82.50,450.06 82.50,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='124.00,450.06 124.00,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='165.51,450.06 165.51,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e3' x='63.82' y='416.23' width='37.35' height='27.09' fill='#595959' fill-opacity='1' stroke='none' data-id='1' title='Dem_Desc&amp;lt;br/&amp;gt;Entirely rural&amp;lt;br/&amp;gt;N = 7,219&amp;lt;br/&amp;gt;Percent: 14.2%'/>\\n   <rect id='svg_39808f443929a61b_e4' x='105.32' y='308.44' width='37.35' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='2' title='Dem_Desc&amp;lt;br/&amp;gt;Town/rural mix&amp;lt;br/&amp;gt;N = 35,940&amp;lt;br/&amp;gt;Percent: 70.7%'/>\\n   <rect id='svg_39808f443929a61b_e5' x='146.83' y='414.53' width='37.35' height='28.79' fill='#595959' fill-opacity='1' stroke='none' data-id='3' title='Dem_Desc&amp;lt;br/&amp;gt;Urban/town/rural mix&amp;lt;br/&amp;gt;N = 7,671&amp;lt;br/&amp;gt;Percent: 15.1%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c4)'>\\n   <rect x='57.59' y='560.53' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='57.59,702.16 190.41,702.16' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,649.84 190.41,649.84' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,597.52 190.41,597.52' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='93.82,708.90 93.82,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='154.19,708.90 154.19,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e6' x='66.65' y='571.1' width='54.33' height='131.06' fill='#595959' fill-opacity='1' stroke='none' data-id='4' title='Gender&amp;lt;br/&amp;gt;F&amp;lt;br/&amp;gt;N = 25,050&amp;lt;br/&amp;gt;Percent: 49.3%'/>\\n   <rect id='svg_39808f443929a61b_e7' x='127.02' y='567.28' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='5' title='Gender&amp;lt;br/&amp;gt;M&amp;lt;br/&amp;gt;N = 25,780&amp;lt;br/&amp;gt;Percent: 50.7%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c5)'>\\n   <rect x='57.59' y='808' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='57.59,949.62 190.41,949.62' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,912.62 190.41,912.62' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,875.61 190.41,875.61' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,838.61 190.41,838.61' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='62.51,956.37 62.51,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='70.71,956.37 70.71,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='78.91,956.37 78.91,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='87.11,956.37 87.11,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='95.31,956.37 95.31,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='103.50,956.37 103.50,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='111.70,956.37 111.70,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='119.90,956.37 119.90,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='128.10,956.37 128.10,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='136.30,956.37 136.30,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='144.50,956.37 144.50,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='152.70,956.37 152.70,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='160.90,956.37 160.90,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='169.09,956.37 169.09,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='177.29,956.37 177.29,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='185.49,956.37 185.49,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e8' x='58.82' y='814.74' width='7.38' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='43' title='hs.grad.year&amp;lt;br/&amp;gt;2008&amp;lt;br/&amp;gt;N = 3,645&amp;lt;br/&amp;gt;Percent: 7.2%'/>\\n   <rect id='svg_39808f443929a61b_e9' x='67.02' y='823.7' width='7.38' height='125.93' fill='#595959' fill-opacity='1' stroke='none' data-id='44' title='hs.grad.year&amp;lt;br/&amp;gt;2009&amp;lt;br/&amp;gt;N = 3,403&amp;lt;br/&amp;gt;Percent: 6.7%'/>\\n   <rect id='svg_39808f443929a61b_e10' x='75.22' y='823.99' width='7.38' height='125.63' fill='#595959' fill-opacity='1' stroke='none' data-id='45' title='hs.grad.year&amp;lt;br/&amp;gt;2010&amp;lt;br/&amp;gt;N = 3,395&amp;lt;br/&amp;gt;Percent: 6.7%'/>\\n   <rect id='svg_39808f443929a61b_e11' x='83.42' y='825.1' width='7.38' height='124.52' fill='#595959' fill-opacity='1' stroke='none' data-id='46' title='hs.grad.year&amp;lt;br/&amp;gt;2011&amp;lt;br/&amp;gt;N = 3,365&amp;lt;br/&amp;gt;Percent: 6.6%'/>\\n   <rect id='svg_39808f443929a61b_e12' x='91.62' y='835.02' width='7.38' height='114.6' fill='#595959' fill-opacity='1' stroke='none' data-id='47' title='hs.grad.year&amp;lt;br/&amp;gt;2012&amp;lt;br/&amp;gt;N = 3,097&amp;lt;br/&amp;gt;Percent: 6.1%'/>\\n   <rect id='svg_39808f443929a61b_e13' x='99.82' y='832.87' width='7.38' height='116.75' fill='#595959' fill-opacity='1' stroke='none' data-id='48' title='hs.grad.year&amp;lt;br/&amp;gt;2013&amp;lt;br/&amp;gt;N = 3,155&amp;lt;br/&amp;gt;Percent: 6.2%'/>\\n   <rect id='svg_39808f443929a61b_e14' x='108.01' y='837.76' width='7.38' height='111.87' fill='#595959' fill-opacity='1' stroke='none' data-id='49' title='hs.grad.year&amp;lt;br/&amp;gt;2014&amp;lt;br/&amp;gt;N = 3,023&amp;lt;br/&amp;gt;Percent: 5.9%'/>\\n   <rect id='svg_39808f443929a61b_e15' x='116.21' y='833.91' width='7.38' height='115.71' fill='#595959' fill-opacity='1' stroke='none' data-id='50' title='hs.grad.year&amp;lt;br/&amp;gt;2015&amp;lt;br/&amp;gt;N = 3,127&amp;lt;br/&amp;gt;Percent: 6.2%'/>\\n   <rect id='svg_39808f443929a61b_e16' x='124.41' y='838.42' width='7.38' height='111.2' fill='#595959' fill-opacity='1' stroke='none' data-id='51' title='hs.grad.year&amp;lt;br/&amp;gt;2016&amp;lt;br/&amp;gt;N = 3,005&amp;lt;br/&amp;gt;Percent: 5.9%'/>\\n   <rect id='svg_39808f443929a61b_e17' x='132.61' y='837.17' width='7.38' height='112.46' fill='#595959' fill-opacity='1' stroke='none' data-id='52' title='hs.grad.year&amp;lt;br/&amp;gt;2017&amp;lt;br/&amp;gt;N = 3,039&amp;lt;br/&amp;gt;Percent: 6.0%'/>\\n   <rect id='svg_39808f443929a61b_e18' x='140.81' y='839.42' width='7.38' height='110.2' fill='#595959' fill-opacity='1' stroke='none' data-id='53' title='hs.grad.year&amp;lt;br/&amp;gt;2018&amp;lt;br/&amp;gt;N = 2,978&amp;lt;br/&amp;gt;Percent: 5.9%'/>\\n   <rect id='svg_39808f443929a61b_e19' x='149.01' y='833.91' width='7.38' height='115.71' fill='#595959' fill-opacity='1' stroke='none' data-id='54' title='hs.grad.year&amp;lt;br/&amp;gt;2019&amp;lt;br/&amp;gt;N = 3,127&amp;lt;br/&amp;gt;Percent: 6.2%'/>\\n   <rect id='svg_39808f443929a61b_e20' x='157.21' y='834.43' width='7.38' height='115.2' fill='#595959' fill-opacity='1' stroke='none' data-id='55' title='hs.grad.year&amp;lt;br/&amp;gt;2020&amp;lt;br/&amp;gt;N = 3,113&amp;lt;br/&amp;gt;Percent: 6.1%'/>\\n   <rect id='svg_39808f443929a61b_e21' x='165.4' y='836.31' width='7.38' height='113.31' fill='#595959' fill-opacity='1' stroke='none' data-id='56' title='hs.grad.year&amp;lt;br/&amp;gt;2021&amp;lt;br/&amp;gt;N = 3,062&amp;lt;br/&amp;gt;Percent: 6.0%'/>\\n   <rect id='svg_39808f443929a61b_e22' x='173.6' y='831.62' width='7.38' height='118.01' fill='#595959' fill-opacity='1' stroke='none' data-id='57' title='hs.grad.year&amp;lt;br/&amp;gt;2022&amp;lt;br/&amp;gt;N = 3,189&amp;lt;br/&amp;gt;Percent: 6.3%'/>\\n   <rect id='svg_39808f443929a61b_e23' x='181.8' y='834.65' width='7.38' height='114.97' fill='#595959' fill-opacity='1' stroke='none' data-id='58' title='hs.grad.year&amp;lt;br/&amp;gt;2023&amp;lt;br/&amp;gt;N = 3,107&amp;lt;br/&amp;gt;Percent: 6.1%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c6)'>\\n   <rect x='57.59' y='1021.46' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='57.59,1163.09 190.41,1163.09' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1112.47 190.41,1112.47' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1061.84 190.41,1061.84' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='64.12,1169.83 64.12,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='75.01,1169.83 75.01,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='85.90,1169.83 85.90,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='96.78,1169.83 96.78,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='107.67,1169.83 107.67,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='118.56,1169.83 118.56,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='129.44,1169.83 129.44,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='140.33,1169.83 140.33,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='151.22,1169.83 151.22,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='162.10,1169.83 162.10,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='172.99,1169.83 172.99,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='183.88,1169.83 183.88,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e24' x='59.23' y='1061.13' width='9.8' height='101.96' fill='#595959' fill-opacity='1' stroke='none' data-id='64' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 10,070&amp;lt;br/&amp;gt;Percent: 19.8%'/>\\n   <rect id='svg_39808f443929a61b_e25' x='70.11' y='1140.5' width='9.8' height='22.59' fill='#595959' fill-opacity='1' stroke='none' data-id='65' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;10&amp;lt;br/&amp;gt;N = 2,231&amp;lt;br/&amp;gt;Percent: 4.4%'/>\\n   <rect id='svg_39808f443929a61b_e26' x='81' y='1129.57' width='9.8' height='33.52' fill='#595959' fill-opacity='1' stroke='none' data-id='66' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;2&amp;lt;br/&amp;gt;N = 3,311&amp;lt;br/&amp;gt;Percent: 6.5%'/>\\n   <rect id='svg_39808f443929a61b_e27' x='91.89' y='1159.98' width='9.8' height='3.11' fill='#595959' fill-opacity='1' stroke='none' data-id='67' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;3&amp;lt;br/&amp;gt;N = 307&amp;lt;br/&amp;gt;Percent: 0.6%'/>\\n   <rect id='svg_39808f443929a61b_e28' x='102.77' y='1071.92' width='9.8' height='91.17' fill='#595959' fill-opacity='1' stroke='none' data-id='68' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;4&amp;lt;br/&amp;gt;N = 9,005&amp;lt;br/&amp;gt;Percent: 17.7%'/>\\n   <rect id='svg_39808f443929a61b_e29' x='113.66' y='1163.02' width='9.8' height='0.07' fill='#595959' fill-opacity='1' stroke='none' data-id='69' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;5&amp;lt;br/&amp;gt;N = 7&amp;lt;br/&amp;gt;Percent: 0.0%'/>\\n   <rect id='svg_39808f443929a61b_e30' x='124.55' y='1162.8' width='9.8' height='0.29' fill='#595959' fill-opacity='1' stroke='none' data-id='70' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;6&amp;lt;br/&amp;gt;N = 29&amp;lt;br/&amp;gt;Percent: 0.1%'/>\\n   <rect id='svg_39808f443929a61b_e31' x='135.43' y='1163.08' width='9.8' height='0.01' fill='#595959' fill-opacity='1' stroke='none' data-id='71' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;8&amp;lt;br/&amp;gt;N = 1&amp;lt;br/&amp;gt;Percent: 0.0%'/>\\n   <rect id='svg_39808f443929a61b_e32' x='146.32' y='1162.71' width='9.8' height='0.37' fill='#595959' fill-opacity='1' stroke='none' data-id='72' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;9&amp;lt;br/&amp;gt;N = 37&amp;lt;br/&amp;gt;Percent: 0.1%'/>\\n   <rect id='svg_39808f443929a61b_e33' x='157.21' y='1126.23' width='9.8' height='36.86' fill='#595959' fill-opacity='1' stroke='none' data-id='73' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;Attending ps&amp;lt;br/&amp;gt;N = 3,641&amp;lt;br/&amp;gt;Percent: 7.2%'/>\\n   <rect id='svg_39808f443929a61b_e34' x='168.09' y='1073.29' width='9.8' height='89.8' fill='#595959' fill-opacity='1' stroke='none' data-id='74' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;Did not grad&amp;lt;br/&amp;gt;N = 8,869&amp;lt;br/&amp;gt;Percent: 17.4%'/>\\n   <rect id='svg_39808f443929a61b_e35' x='178.98' y='1028.21' width='9.8' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='75' title='ps.grad.InstitutionSector&amp;lt;br/&amp;gt;Never attended ps&amp;lt;br/&amp;gt;N = 13,322&amp;lt;br/&amp;gt;Percent: 26.2%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c7)'>\\n   <rect x='57.59' y='1250.7' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='57.59,1392.33 190.41,1392.33' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1365.65 190.41,1365.65' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1338.96 190.41,1338.96' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1312.28 190.41,1312.28' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1285.60 190.41,1285.60' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='57.59,1258.92 190.41,1258.92' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='93.82,1399.07 93.82,1250.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='154.19,1399.07 154.19,1250.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e36' x='66.65' y='1257.45' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='85' title='sat.taken&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 50,551&amp;lt;br/&amp;gt;Percent: 99.5%'/>\\n   <rect id='svg_39808f443929a61b_e37' x='127.02' y='1391.58' width='54.33' height='0.74' fill='#595959' fill-opacity='1' stroke='none' data-id='86' title='sat.taken&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 279&amp;lt;br/&amp;gt;Percent: 0.5%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c8)'>\\n   <rect x='232.3' y='45.66' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='232.30,187.29 365.11,187.29' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,151.33 365.11,151.33' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,115.37 365.11,115.37' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,79.40 365.11,79.40' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='268.52,194.03 268.52,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='328.89,194.03 328.89,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e38' x='241.35' y='139.38' width='54.33' height='47.91' fill='#595959' fill-opacity='1' stroke='none' data-id='20' title='attended.ps&amp;lt;br/&amp;gt;No&amp;lt;br/&amp;gt;N = 13,322&amp;lt;br/&amp;gt;Percent: 26.2%'/>\\n   <rect id='svg_39808f443929a61b_e39' x='301.72' y='52.4' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='21' title='attended.ps&amp;lt;br/&amp;gt;Yes&amp;lt;br/&amp;gt;N = 37,508&amp;lt;br/&amp;gt;Percent: 73.8%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c9)'>\\n   <rect x='232.3' y='301.69' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='232.30,443.32 365.11,443.32' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,400.98 365.11,400.98' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,358.64 365.11,358.64' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,316.30 365.11,316.30' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='268.52,450.06 268.52,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='328.89,450.06 328.89,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e40' x='241.35' y='308.44' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='28' title='economic.status&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 31,858&amp;lt;br/&amp;gt;Percent: 62.7%'/>\\n   <rect id='svg_39808f443929a61b_e41' x='301.72' y='362.99' width='54.33' height='80.32' fill='#595959' fill-opacity='1' stroke='none' data-id='29' title='economic.status&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 18,972&amp;lt;br/&amp;gt;Percent: 37.3%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c10)'>\\n   <rect x='232.3' y='560.53' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='232.30,702.16 365.11,702.16' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,667.00 365.11,667.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,631.83 365.11,631.83' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,596.67 365.11,596.67' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,561.51 365.11,561.51' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='268.52,708.90 268.52,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='328.89,708.90 328.89,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e42' x='241.35' y='658.31' width='54.33' height='43.85' fill='#595959' fill-opacity='1' stroke='none' data-id='35' title='grad.year.covid&amp;lt;br/&amp;gt;Post-covid grad&amp;lt;br/&amp;gt;N = 12,471&amp;lt;br/&amp;gt;Percent: 24.5%'/>\\n   <rect id='svg_39808f443929a61b_e43' x='301.72' y='567.28' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='36' title='grad.year.covid&amp;lt;br/&amp;gt;Pre-covid grad&amp;lt;br/&amp;gt;N = 38,359&amp;lt;br/&amp;gt;Percent: 75.5%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c11)'>\\n   <rect x='232.3' y='808' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='232.30,949.62 365.11,949.62' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,922.34 365.11,922.34' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,895.05 365.11,895.05' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,867.76 365.11,867.76' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,840.48 365.11,840.48' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,813.19 365.11,813.19' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='268.52,956.37 268.52,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='328.89,956.37 328.89,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e44' x='241.35' y='814.74' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='8' title='LimitedEnglishProficiencyIndicator&amp;lt;br/&amp;gt;N&amp;lt;br/&amp;gt;N = 49,432&amp;lt;br/&amp;gt;Percent: 97.2%'/>\\n   <rect id='svg_39808f443929a61b_e45' x='301.72' y='945.81' width='54.33' height='3.81' fill='#595959' fill-opacity='1' stroke='none' data-id='9' title='LimitedEnglishProficiencyIndicator&amp;lt;br/&amp;gt;Y&amp;lt;br/&amp;gt;N = 1,398&amp;lt;br/&amp;gt;Percent: 2.8%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c12)'>\\n   <rect x='232.3' y='1021.46' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='232.30,1163.09 365.11,1163.09' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1132.70 365.11,1132.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1102.31 365.11,1102.31' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1071.92 365.11,1071.92' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1041.52 365.11,1041.52' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='245.15,1169.83 245.15,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='266.57,1169.83 266.57,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='287.99,1169.83 287.99,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='309.42,1169.83 309.42,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='330.84,1169.83 330.84,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='352.26,1169.83 352.26,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e46' x='235.51' y='1140.96' width='19.28' height='22.13' fill='#595959' fill-opacity='1' stroke='none' data-id='76' title='ps.grad.location&amp;lt;br/&amp;gt;Attending ps&amp;lt;br/&amp;gt;N = 3,641&amp;lt;br/&amp;gt;Percent: 7.2%'/>\\n   <rect id='svg_39808f443929a61b_e47' x='256.93' y='1028.21' width='19.28' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='77' title='ps.grad.location&amp;lt;br/&amp;gt;Did not graduate ps&amp;lt;br/&amp;gt;N = 22,191&amp;lt;br/&amp;gt;Percent: 43.7%'/>\\n   <rect id='svg_39808f443929a61b_e48' x='278.35' y='1107.9' width='19.28' height='55.19' fill='#595959' fill-opacity='1' stroke='none' data-id='78' title='ps.grad.location&amp;lt;br/&amp;gt;PS grad MN&amp;lt;br/&amp;gt;N = 9,080&amp;lt;br/&amp;gt;Percent: 17.9%'/>\\n   <rect id='svg_39808f443929a61b_e49' x='342.62' y='1140.2' width='19.28' height='22.88' fill='#595959' fill-opacity='1' stroke='none' data-id='79' title='ps.grad.location&amp;lt;br/&amp;gt;PS grad Region&amp;lt;br/&amp;gt;N = 3,765&amp;lt;br/&amp;gt;Percent: 7.4%'/>\\n   <rect id='svg_39808f443929a61b_e50' x='299.78' y='1113.11' width='19.28' height='49.98' fill='#595959' fill-opacity='1' stroke='none' data-id='80' title='ps.grad.location&amp;lt;br/&amp;gt;PS grad outside MN&amp;lt;br/&amp;gt;N = 8,222&amp;lt;br/&amp;gt;Percent: 16.2%'/>\\n   <rect id='svg_39808f443929a61b_e51' x='321.2' y='1139.2' width='19.28' height='23.89' fill='#595959' fill-opacity='1' stroke='none' data-id='81' title='ps.grad.location&amp;lt;br/&amp;gt;PS grad region&amp;lt;br/&amp;gt;N = 3,931&amp;lt;br/&amp;gt;Percent: 7.7%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c13)'>\\n   <rect x='232.3' y='1250.7' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='232.30,1392.33 365.11,1392.33' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1361.59 365.11,1361.59' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1330.85 365.11,1330.85' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1300.11 365.11,1300.11' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='232.30,1269.37 365.11,1269.37' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='268.52,1399.07 268.52,1250.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='328.89,1399.07 328.89,1250.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e52' x='241.35' y='1257.45' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='16' title='SpecialEdStatus&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 43,879&amp;lt;br/&amp;gt;Percent: 86.3%'/>\\n   <rect id='svg_39808f443929a61b_e53' x='301.72' y='1370.96' width='54.33' height='21.37' fill='#595959' fill-opacity='1' stroke='none' data-id='17' title='SpecialEdStatus&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 6,951&amp;lt;br/&amp;gt;Percent: 13.7%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c14)'>\\n   <rect x='407' y='45.66' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='407.00,187.29 539.82,187.29' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,148.99 539.82,148.99' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,110.68 539.82,110.68' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,72.38 539.82,72.38' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='431.90,194.03 431.90,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='473.41,194.03 473.41,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='514.91,194.03 514.91,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e54' x='413.23' y='136.26' width='37.35' height='51.03' fill='#595959' fill-opacity='1' stroke='none' data-id='22' title='attended.ps.within.first.year.hsgrad&amp;lt;br/&amp;gt;Did not attend ps&amp;lt;br/&amp;gt;N = 13,322&amp;lt;br/&amp;gt;Percent: 26.2%'/>\\n   <rect id='svg_39808f443929a61b_e55' x='454.73' y='178.51' width='37.35' height='8.78' fill='#595959' fill-opacity='1' stroke='none' data-id='23' title='attended.ps.within.first.year.hsgrad&amp;lt;br/&amp;gt;No&amp;lt;br/&amp;gt;N = 2,292&amp;lt;br/&amp;gt;Percent: 4.5%'/>\\n   <rect id='svg_39808f443929a61b_e56' x='496.24' y='52.4' width='37.35' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='24' title='attended.ps.within.first.year.hsgrad&amp;lt;br/&amp;gt;Yes&amp;lt;br/&amp;gt;N = 35,216&amp;lt;br/&amp;gt;Percent: 69.3%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c15)'>\\n   <rect x='407' y='301.69' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='407.00,443.32 539.82,443.32' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,413.83 539.82,413.83' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,384.33 539.82,384.33' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,354.84 539.82,354.84' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,325.34 539.82,325.34' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='431.90,450.06 431.90,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='473.41,450.06 473.41,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='514.91,450.06 514.91,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e57' x='413.23' y='335.29' width='37.35' height='108.03' fill='#595959' fill-opacity='1' stroke='none' data-id='30' title='edr&amp;lt;br/&amp;gt;EDR 6E- Southwest Central&amp;lt;br/&amp;gt;N = 18,313&amp;lt;br/&amp;gt;Percent: 36.0%'/>\\n   <rect id='svg_39808f443929a61b_e58' x='454.73' y='386.39' width='37.35' height='56.93' fill='#595959' fill-opacity='1' stroke='none' data-id='31' title='edr&amp;lt;br/&amp;gt;EDR 6W- Upper Minnesota Valley&amp;lt;br/&amp;gt;N = 9,651&amp;lt;br/&amp;gt;Percent: 19.0%'/>\\n   <rect id='svg_39808f443929a61b_e59' x='496.24' y='308.44' width='37.35' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='32' title='edr&amp;lt;br/&amp;gt;EDR 8 - Southwest&amp;lt;br/&amp;gt;N = 22,866&amp;lt;br/&amp;gt;Percent: 45.0%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c16)'>\\n   <rect x='407' y='560.53' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='407.00,702.16 539.82,702.16' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,671.66 539.82,671.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,641.16 539.82,641.16' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,610.66 539.82,610.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,580.17 539.82,580.17' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='419.85,708.90 419.85,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='441.27,708.90 441.27,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='462.70,708.90 462.70,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='484.12,708.90 484.12,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='505.54,708.90 505.54,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='526.96,708.90 526.96,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e60' x='410.21' y='667.12' width='19.28' height='35.04' fill='#595959' fill-opacity='1' stroke='none' data-id='37' title='highest.cred.level&amp;lt;br/&amp;gt;Associate degree&amp;lt;br/&amp;gt;N = 5,744&amp;lt;br/&amp;gt;Percent: 11.3%'/>\\n   <rect id='svg_39808f443929a61b_e61' x='431.63' y='679.95' width='19.28' height='22.21' fill='#595959' fill-opacity='1' stroke='none' data-id='38' title='highest.cred.level&amp;lt;br/&amp;gt;Attending ps&amp;lt;br/&amp;gt;N = 3,641&amp;lt;br/&amp;gt;Percent: 7.2%'/>\\n   <rect id='svg_39808f443929a61b_e62' x='453.06' y='623.29' width='19.28' height='78.87' fill='#595959' fill-opacity='1' stroke='none' data-id='39' title='highest.cred.level&amp;lt;br/&amp;gt;Bachelor degree&amp;lt;br/&amp;gt;N = 12,930&amp;lt;br/&amp;gt;Percent: 25.4%'/>\\n   <rect id='svg_39808f443929a61b_e63' x='474.48' y='567.28' width='19.28' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='40' title='highest.cred.level&amp;lt;br/&amp;gt;Did not graduate ps&amp;lt;br/&amp;gt;N = 22,113&amp;lt;br/&amp;gt;Percent: 43.5%'/>\\n   <rect id='svg_39808f443929a61b_e64' x='495.9' y='675.06' width='19.28' height='27.1' fill='#595959' fill-opacity='1' stroke='none' data-id='41' title='highest.cred.level&amp;lt;br/&amp;gt;Less than Associate Degree&amp;lt;br/&amp;gt;N = 4,443&amp;lt;br/&amp;gt;Percent: 8.7%'/>\\n   <rect id='svg_39808f443929a61b_e65' x='517.32' y='690.21' width='19.28' height='11.95' fill='#595959' fill-opacity='1' stroke='none' data-id='42' title='highest.cred.level&amp;lt;br/&amp;gt;Master degree or higher&amp;lt;br/&amp;gt;N = 1,959&amp;lt;br/&amp;gt;Percent: 3.9%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c17)'>\\n   <rect x='407' y='808' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='407.00,949.62 539.82,949.62' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,920.24 539.82,920.24' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,890.86 539.82,890.86' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,861.48 539.82,861.48' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,832.10 539.82,832.10' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='443.22,956.37 443.22,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='503.59,956.37 503.59,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e66' x='416.06' y='814.74' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='59' title='non.english.home&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 45,909&amp;lt;br/&amp;gt;Percent: 90.3%'/>\\n   <rect id='svg_39808f443929a61b_e67' x='476.43' y='935.17' width='54.33' height='14.46' fill='#595959' fill-opacity='1' stroke='none' data-id='60' title='non.english.home&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 4,921&amp;lt;br/&amp;gt;Percent: 9.7%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c18)'>\\n   <rect x='407' y='1021.46' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='407.00,1163.09 539.82,1163.09' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1134.72 539.82,1134.72' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1106.36 539.82,1106.36' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1077.99 539.82,1077.99' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1049.63 539.82,1049.63' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='431.90,1169.83 431.90,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='473.41,1169.83 473.41,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='514.91,1169.83 514.91,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e68' x='413.23' y='1028.21' width='37.35' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='82' title='pseo.participant&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 23,776&amp;lt;br/&amp;gt;Percent: 46.8%'/>\\n   <rect id='svg_39808f443929a61b_e69' x='454.73' y='1067.97' width='37.35' height='95.12' fill='#595959' fill-opacity='1' stroke='none' data-id='83' title='pseo.participant&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 16,767&amp;lt;br/&amp;gt;Percent: 33.0%'/>\\n   <rect id='svg_39808f443929a61b_e70' x='496.24' y='1104.73' width='37.35' height='58.36' fill='#595959' fill-opacity='1' stroke='none' data-id='84' title='pseo.participant&amp;lt;br/&amp;gt;NA&amp;lt;br/&amp;gt;N = 10,287&amp;lt;br/&amp;gt;Percent: 20.2%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c19)'>\\n   <rect x='407' y='1250.7' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='407.00,1392.33 539.82,1392.33' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1352.27 539.82,1352.27' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1312.21 539.82,1312.21' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='407.00,1272.15 539.82,1272.15' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='443.22,1399.07 443.22,1250.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='503.59,1399.07 503.59,1250.70' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e71' x='416.06' y='1323.59' width='54.33' height='68.74' fill='#595959' fill-opacity='1' stroke='none' data-id='87' title='took.ACT&amp;lt;br/&amp;gt;No&amp;lt;br/&amp;gt;N = 17,160&amp;lt;br/&amp;gt;Percent: 33.8%'/>\\n   <rect id='svg_39808f443929a61b_e72' x='476.43' y='1257.45' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='88' title='took.ACT&amp;lt;br/&amp;gt;Yes&amp;lt;br/&amp;gt;N = 33,670&amp;lt;br/&amp;gt;Percent: 66.2%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c20)'>\\n   <rect x='581.7' y='45.66' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='581.70,187.29 714.52,187.29' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,135.50 714.52,135.50' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,83.71 714.52,83.71' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='606.61,194.03 606.61,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='648.11,194.03 648.11,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='689.62,194.03 689.62,45.66' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e73' x='587.93' y='52.4' width='37.35' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='25' title='cte.achievement&amp;lt;br/&amp;gt;CTE Concentrator or Completor&amp;lt;br/&amp;gt;N = 26,044&amp;lt;br/&amp;gt;Percent: 51.2%'/>\\n   <rect id='svg_39808f443929a61b_e74' x='629.43' y='112.63' width='37.35' height='74.66' fill='#595959' fill-opacity='1' stroke='none' data-id='26' title='cte.achievement&amp;lt;br/&amp;gt;CTE Participant&amp;lt;br/&amp;gt;N = 14,416&amp;lt;br/&amp;gt;Percent: 28.4%'/>\\n   <rect id='svg_39808f443929a61b_e75' x='670.94' y='133.58' width='37.35' height='53.71' fill='#595959' fill-opacity='1' stroke='none' data-id='27' title='cte.achievement&amp;lt;br/&amp;gt;No CTE&amp;lt;br/&amp;gt;N = 10,370&amp;lt;br/&amp;gt;Percent: 20.4%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c21)'>\\n   <rect x='581.7' y='301.69' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='581.70,443.32 714.52,443.32' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,413.85 714.52,413.85' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,384.38 714.52,384.38' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,354.90 714.52,354.90' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,325.43 714.52,325.43' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='617.93,450.06 617.93,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='678.30,450.06 678.30,301.69' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e76' x='590.76' y='308.44' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='33' title='english.learner&amp;lt;br/&amp;gt;0&amp;lt;br/&amp;gt;N = 45,767&amp;lt;br/&amp;gt;Percent: 90.0%'/>\\n   <rect id='svg_39808f443929a61b_e77' x='651.13' y='428.4' width='54.33' height='14.92' fill='#595959' fill-opacity='1' stroke='none' data-id='34' title='english.learner&amp;lt;br/&amp;gt;1&amp;lt;br/&amp;gt;N = 5,063&amp;lt;br/&amp;gt;Percent: 10.0%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c22)'>\\n   <rect x='581.7' y='560.53' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='581.70,702.16 714.52,702.16' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,675.50 714.52,675.50' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,648.84 714.52,648.84' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,622.18 714.52,622.18' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,595.52 714.52,595.52' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,568.86 714.52,568.86' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='617.93,708.90 617.93,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='678.30,708.90 678.30,560.53' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e78' x='590.76' y='567.28' width='54.33' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='6' title='HomelessIndicator&amp;lt;br/&amp;gt;N&amp;lt;br/&amp;gt;N = 50,595&amp;lt;br/&amp;gt;Percent: 99.5%'/>\\n   <rect id='svg_39808f443929a61b_e79' x='651.13' y='701.53' width='54.33' height='0.63' fill='#595959' fill-opacity='1' stroke='none' data-id='7' title='HomelessIndicator&amp;lt;br/&amp;gt;Y&amp;lt;br/&amp;gt;N = 235&amp;lt;br/&amp;gt;Percent: 0.5%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c23)'>\\n   <rect x='581.7' y='808' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='581.70,949.62 714.52,949.62' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,922.73 714.52,922.73' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,895.83 714.52,895.83' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,868.94 714.52,868.94' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,842.04 714.52,842.04' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,815.15 714.52,815.15' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='606.61,956.37 606.61,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='648.11,956.37 648.11,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='689.62,956.37 689.62,808.00' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e80' x='587.93' y='930.04' width='37.35' height='19.58' fill='#595959' fill-opacity='1' stroke='none' data-id='61' title='ps.grad&amp;lt;br/&amp;gt;Attending ps&amp;lt;br/&amp;gt;N = 3,641&amp;lt;br/&amp;gt;Percent: 7.2%'/>\\n   <rect id='svg_39808f443929a61b_e81' x='629.43' y='830.68' width='37.35' height='118.94' fill='#595959' fill-opacity='1' stroke='none' data-id='62' title='ps.grad&amp;lt;br/&amp;gt;No&amp;lt;br/&amp;gt;N = 22,113&amp;lt;br/&amp;gt;Percent: 43.5%'/>\\n   <rect id='svg_39808f443929a61b_e82' x='670.94' y='814.74' width='37.35' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='63' title='ps.grad&amp;lt;br/&amp;gt;Y&amp;lt;br/&amp;gt;N = 25,076&amp;lt;br/&amp;gt;Percent: 49.3%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c24)'>\\n   <rect x='581.7' y='1021.46' width='132.82' height='148.37' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <polyline points='581.70,1163.09 714.52,1163.09' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,1125.22 714.52,1125.22' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,1087.35 714.52,1087.35' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='581.70,1049.48 714.52,1049.48' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='594.56,1169.83 594.56,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='615.98,1169.83 615.98,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='637.40,1169.83 637.40,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='658.82,1169.83 658.82,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='680.24,1169.83 680.24,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='701.67,1169.83 701.67,1021.46' fill='none' stroke='#B3B3B3' stroke-opacity='1' stroke-width='0.21' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <rect id='svg_39808f443929a61b_e83' x='584.92' y='1160.76' width='19.28' height='2.33' fill='#595959' fill-opacity='1' stroke='none' data-id='10' title='RaceEthnicity&amp;lt;br/&amp;gt;AI&amp;lt;br/&amp;gt;N = 614&amp;lt;br/&amp;gt;Percent: 1.2%'/>\\n   <rect id='svg_39808f443929a61b_e84' x='606.34' y='1158.5' width='19.28' height='4.59' fill='#595959' fill-opacity='1' stroke='none' data-id='11' title='RaceEthnicity&amp;lt;br/&amp;gt;Asian/PI&amp;lt;br/&amp;gt;N = 1,212&amp;lt;br/&amp;gt;Percent: 2.4%'/>\\n   <rect id='svg_39808f443929a61b_e85' x='627.76' y='1159.86' width='19.28' height='3.23' fill='#595959' fill-opacity='1' stroke='none' data-id='12' title='RaceEthnicity&amp;lt;br/&amp;gt;Black&amp;lt;br/&amp;gt;N = 854&amp;lt;br/&amp;gt;Percent: 1.7%'/>\\n   <rect id='svg_39808f443929a61b_e86' x='649.18' y='1150.66' width='19.28' height='12.43' fill='#595959' fill-opacity='1' stroke='none' data-id='13' title='RaceEthnicity&amp;lt;br/&amp;gt;Hispanic&amp;lt;br/&amp;gt;N = 3,282&amp;lt;br/&amp;gt;Percent: 6.5%'/>\\n   <rect id='svg_39808f443929a61b_e87' x='670.6' y='1128.06' width='19.28' height='35.03' fill='#595959' fill-opacity='1' stroke='none' data-id='14' title='RaceEthnicity&amp;lt;br/&amp;gt;Unknown&amp;lt;br/&amp;gt;N = 9,250&amp;lt;br/&amp;gt;Percent: 18.2%'/>\\n   <rect id='svg_39808f443929a61b_e88' x='692.03' y='1028.21' width='19.28' height='134.88' fill='#595959' fill-opacity='1' stroke='none' data-id='15' title='RaceEthnicity&amp;lt;br/&amp;gt;White&amp;lt;br/&amp;gt;N = 35,618&amp;lt;br/&amp;gt;Percent: 70.1%'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c25)'>\\n   <rect x='57.59' y='1231.57' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='101.3' y='1245.14' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>sat.taken<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c26)'>\\n   <rect x='232.3' y='1231.57' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='257.65' y='1245.14' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>SpecialEdStatus<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c27)'>\\n   <rect x='407' y='1231.57' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='450.09' y='1245.14' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>took.ACT<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c28)'>\\n   <rect x='57.59' y='1002.33' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='63.67' y='1015.9' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>ps.grad.InstitutionSector<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c29)'>\\n   <rect x='232.3' y='1002.33' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='259.21' y='1015.9' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>ps.grad.location<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c30)'>\\n   <rect x='407' y='1002.33' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='433.92' y='1015.9' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>pseo.participant<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c31)'>\\n   <rect x='581.7' y='1002.33' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='613.91' y='1015.9' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>RaceEthnicity<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c32)'>\\n   <rect x='57.59' y='788.86' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='92.9' y='802.44' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>hs.grad.year<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c33)'>\\n   <rect x='232.3' y='788.86' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='213.51' y='802.44' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>LimitedEnglishProficiencyIndicator<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c34)'>\\n   <rect x='407' y='788.86' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='429.25' y='802.44' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>non.english.home<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c35)'>\\n   <rect x='581.7' y='788.86' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='629.45' y='802.44' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>ps.grad<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c36)'>\\n   <rect x='57.59' y='541.4' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='105.34' y='554.97' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>Gender<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c37)'>\\n   <rect x='232.3' y='541.4' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='260.77' y='554.97' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>grad.year.covid<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c38)'>\\n   <rect x='407' y='541.4' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='429.88' y='554.97' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>highest.cred.level<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c39)'>\\n   <rect x='581.7' y='541.4' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='601.79' y='554.97' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>HomelessIndicator<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c40)'>\\n   <rect x='57.59' y='282.56' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='96.34' y='296.13' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>Dem_Desc<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c41)'>\\n   <rect x='232.3' y='282.56' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='258.28' y='296.13' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>economic.status<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c42)'>\\n   <rect x='407' y='282.56' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='465.32' y='296.13' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>edr<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c43)'>\\n   <rect x='581.7' y='282.56' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='611.42' y='296.13' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>english.learner<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c44)'>\\n   <rect x='57.59' y='26.53' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='102.55' y='40.1' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>ap.exam<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c45)'>\\n   <rect x='232.3' y='26.53' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='269.47' y='40.1' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>attended.ps<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c46)'>\\n   <rect x='407' y='26.53' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='386.96' y='40.1' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>attended.ps.within.first.year.hsgrad<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c47)'>\\n   <rect x='581.7' y='26.53' width='132.82' height='19.14' fill='#D9D9D9' fill-opacity='1' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n   <text x='607.38' y='40.1' font-size='8.4pt' font-family='Arial' fill='#1A1A1A' fill-opacity='1'>cte.achievement<\\/text>\\n  <\\/g>\\n  <g clip-path='url(#svg_39808f443929a61b_c1)'>\\n   <text transform='translate(92.13,1410.89) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(152.50,1410.89) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(266.83,1410.89) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(327.20,1410.89) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(434.45,1414.20) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>No<\\/text>\\n   <text transform='translate(491.25,1415.86) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Yes<\\/text>\\n   <text transform='translate(62.44,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(68.25,1184.02) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10<\\/text>\\n   <text transform='translate(84.21,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2<\\/text>\\n   <text transform='translate(95.10,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>3<\\/text>\\n   <text transform='translate(105.98,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>4<\\/text>\\n   <text transform='translate(116.87,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5<\\/text>\\n   <text transform='translate(127.76,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>6<\\/text>\\n   <text transform='translate(138.64,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>8<\\/text>\\n   <text transform='translate(149.53,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>9<\\/text>\\n   <text transform='translate(109.73,1205.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Attending ps<\\/text>\\n   <text transform='translate(122.64,1204.35) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Did not grad<\\/text>\\n   <text transform='translate(108.15,1216.18) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Never attended ps<\\/text>\\n   <text transform='translate(192.77,1205.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Attending ps<\\/text>\\n   <text transform='translate(184.27,1219.24) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Did not graduate ps<\\/text>\\n   <text transform='translate(240.16,1203.17) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>PS grad MN<\\/text>\\n   <text transform='translate(226.59,1219.49) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>PS grad outside MN<\\/text>\\n   <text transform='translate(269.31,1209.56) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>PS grad region<\\/text>\\n   <text transform='translate(287.70,1210.97) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>PS grad Region<\\/text>\\n   <text transform='translate(430.22,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(471.72,1181.65) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(505.12,1185.43) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>NA<\\/text>\\n   <text transform='translate(588.82,1183.54) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>AI<\\/text>\\n   <text transform='translate(583.35,1196.08) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Asian/PI<\\/text>\\n   <text transform='translate(616.44,1190.64) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Black<\\/text>\\n   <text transform='translate(624.18,1197.02) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Hispanic<\\/text>\\n   <text transform='translate(642.57,1198.43) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Unknown<\\/text>\\n   <text transform='translate(680.21,1190.87) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>White<\\/text>\\n   <text transform='translate(45.60,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2008<\\/text>\\n   <text transform='translate(53.80,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2009<\\/text>\\n   <text transform='translate(62.00,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2010<\\/text>\\n   <text transform='translate(70.70,975.05) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2011<\\/text>\\n   <text transform='translate(78.40,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2012<\\/text>\\n   <text transform='translate(86.59,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2013<\\/text>\\n   <text transform='translate(94.79,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2014<\\/text>\\n   <text transform='translate(102.99,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2015<\\/text>\\n   <text transform='translate(111.19,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2016<\\/text>\\n   <text transform='translate(119.39,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2017<\\/text>\\n   <text transform='translate(127.59,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2018<\\/text>\\n   <text transform='translate(135.79,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2019<\\/text>\\n   <text transform='translate(143.99,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2020<\\/text>\\n   <text transform='translate(152.18,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2021<\\/text>\\n   <text transform='translate(160.38,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2022<\\/text>\\n   <text transform='translate(168.58,975.29) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2023<\\/text>\\n   <text transform='translate(265.32,968.90) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>N<\\/text>\\n   <text transform='translate(326.19,968.66) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Y<\\/text>\\n   <text transform='translate(441.53,968.19) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(501.91,968.19) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(554.23,991.83) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Attending ps<\\/text>\\n   <text transform='translate(639.34,971.49) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>No<\\/text>\\n   <text transform='translate(686.91,968.66) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Y<\\/text>\\n   <text transform='translate(91.63,720.96) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>F<\\/text>\\n   <text transform='translate(149.97,721.91) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>M<\\/text>\\n   <text transform='translate(202.94,750.52) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Post-covid grad<\\/text>\\n   <text transform='translate(268.37,748.16) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Pre-covid grad<\\/text>\\n   <text transform='translate(347.67,753.60) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Associate degree<\\/text>\\n   <text transform='translate(388.90,744.36) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Attending ps<\\/text>\\n   <text transform='translate(394.58,751.70) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Bachelor degree<\\/text>\\n   <text transform='translate(401.82,758.31) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Did not graduate ps<\\/text>\\n   <text transform='translate(387.55,774.96) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Less than Associate Degree<\\/text>\\n   <text transform='translate(426.38,766.84) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Master degree or higher<\\/text>\\n   <text transform='translate(614.72,721.43) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>N<\\/text>\\n   <text transform='translate(675.59,721.20) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Y<\\/text>\\n   <text transform='translate(29.57,485.78) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Entirely rural<\\/text>\\n   <text transform='translate(63.15,489.47) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Town/rural mix<\\/text>\\n   <text transform='translate(77.61,502.08) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Urban/town/rural mix<\\/text>\\n   <text transform='translate(266.83,461.88) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(327.20,461.88) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(316.62,514.86) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>EDR 6E- Southwest Central<\\/text>\\n   <text transform='translate(333.46,526.36) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>EDR 6W- Upper Minnesota Valley<\\/text>\\n   <text transform='translate(437.16,497.35) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>EDR 8 - Southwest<\\/text>\\n   <text transform='translate(616.24,461.88) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(676.61,461.88) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(92.13,205.85) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text transform='translate(152.50,205.85) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1<\\/text>\\n   <text transform='translate(259.74,209.16) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>No<\\/text>\\n   <text transform='translate(316.54,210.82) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Yes<\\/text>\\n   <text transform='translate(360.76,238.24) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Did not attend ps<\\/text>\\n   <text transform='translate(464.63,209.16) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>No<\\/text>\\n   <text transform='translate(502.57,210.82) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>Yes<\\/text>\\n   <text transform='translate(472.07,267.80) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>CTE Concentrator or Completor<\\/text>\\n   <text transform='translate(583.54,235.18) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>CTE Participant<\\/text>\\n   <text transform='translate(660.05,218.85) rotate(-25.00)' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>No CTE<\\/text>\\n   <text x='573.29' y='191.29' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='545.3' y='139.5' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='545.3' y='87.71' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='573.29' y='447.33' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='545.3' y='417.85' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='545.3' y='388.38' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='545.3' y='358.91' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='545.3' y='329.44' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='573.29' y='706.17' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='545.3' y='679.51' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='545.3' y='652.85' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='545.3' y='626.19' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='545.3' y='599.53' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='545.3' y='572.87' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>50,000<\\/text>\\n   <text x='573.29' y='953.63' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='551.52' y='926.74' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5,000<\\/text>\\n   <text x='545.3' y='899.84' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='545.3' y='872.95' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>15,000<\\/text>\\n   <text x='545.3' y='846.05' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='545.3' y='819.16' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>25,000<\\/text>\\n   <text x='573.29' y='1167.1' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='545.3' y='1129.23' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='545.3' y='1091.36' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='545.3' y='1053.49' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='398.59' y='191.29' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='370.59' y='152.99' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='370.59' y='114.69' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='370.59' y='76.39' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='398.59' y='447.33' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='376.81' y='417.83' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5,000<\\/text>\\n   <text x='370.59' y='388.34' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='370.59' y='358.84' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>15,000<\\/text>\\n   <text x='370.59' y='329.35' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='398.59' y='706.17' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='376.81' y='675.67' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5,000<\\/text>\\n   <text x='370.59' y='645.17' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='370.59' y='614.67' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>15,000<\\/text>\\n   <text x='370.59' y='584.17' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='398.59' y='953.63' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='370.59' y='924.25' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='370.59' y='894.87' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='370.59' y='865.49' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='370.59' y='836.11' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='398.59' y='1167.1' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='376.81' y='1138.73' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5,000<\\/text>\\n   <text x='370.59' y='1110.37' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='370.59' y='1082' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>15,000<\\/text>\\n   <text x='370.59' y='1053.64' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='398.59' y='1396.34' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='370.59' y='1356.28' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='370.59' y='1316.22' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='370.59' y='1276.16' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='223.88' y='191.29' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='195.89' y='155.33' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='195.89' y='119.37' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='195.89' y='83.41' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='223.88' y='447.33' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='195.89' y='404.99' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='195.89' y='362.65' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='195.89' y='320.31' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='223.88' y='706.17' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='195.89' y='671' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='195.89' y='635.84' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='195.89' y='600.68' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='195.89' y='565.51' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='223.88' y='953.63' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='195.89' y='926.34' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='195.89' y='899.06' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='195.89' y='871.77' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='195.89' y='844.48' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='195.89' y='817.2' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>50,000<\\/text>\\n   <text x='223.88' y='1167.1' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='202.11' y='1136.7' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5,000<\\/text>\\n   <text x='195.89' y='1106.31' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='195.89' y='1075.92' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>15,000<\\/text>\\n   <text x='195.89' y='1045.53' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='223.88' y='1396.34' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='195.89' y='1365.6' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='195.89' y='1334.86' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='195.89' y='1304.12' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='195.89' y='1273.38' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='49.18' y='191.29' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='21.19' y='159.96' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='21.19' y='128.62' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='21.19' y='97.29' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='21.19' y='65.95' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='49.18' y='447.33' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='21.19' y='409.8' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='21.19' y='372.27' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='21.19' y='334.74' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='49.18' y='706.17' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='21.19' y='653.85' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='21.19' y='601.53' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='49.18' y='953.63' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='27.41' y='916.63' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>1,000<\\/text>\\n   <text x='27.41' y='879.62' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>2,000<\\/text>\\n   <text x='27.41' y='842.62' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>3,000<\\/text>\\n   <text x='49.18' y='1167.1' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='27.41' y='1116.47' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>5,000<\\/text>\\n   <text x='21.19' y='1065.85' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='49.18' y='1396.34' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>0<\\/text>\\n   <text x='21.19' y='1369.65' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>10,000<\\/text>\\n   <text x='21.19' y='1342.97' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>20,000<\\/text>\\n   <text x='21.19' y='1316.29' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>30,000<\\/text>\\n   <text x='21.19' y='1289.61' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>40,000<\\/text>\\n   <text x='21.19' y='1262.92' font-size='8.4pt' font-weight='bold' font-family='Arial' fill='#4D4D4D' fill-opacity='1'>50,000<\\/text>\\n   <text x='5.48' y='17.51' font-size='12.6pt' font-weight='bold' font-family='Arial'>N for each independent, categorical variable<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_39808f443929a61b\",\"ratio\":0.5,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { padding:5px;background:black;color:white;border-radius:2px;text-align:left; ; position:absolute;pointer-events:none;z-index:9999;}\",\"placement\":\"doc\",\"opacity\":0.9,\"offx\":10,\"offy\":10,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_data_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_data_SVGID_ { fill:orange;stroke:black; }\\nline.hover_data_SVGID_, polyline.hover_data_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_data_SVGID_, polygon.hover_data_SVGID_, path.hover_data_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_data_SVGID_ { stroke:orange; }\",\"reactive\":true,\"nearest_distance\":null,\"linked\":false},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_data_SVGID_ { stroke:none;fill:red; }\\ncircle.select_data_SVGID_ { fill:red;stroke:black; }\\nline.select_data_SVGID_, polyline.select_data_SVGID_ { fill:none;stroke:red; }\\nrect.select_data_SVGID_, polygon.select_data_SVGID_, path.select_data_SVGID_ { fill:red;stroke:none; }\\nimage.select_data_SVGID_ { stroke:red; }\",\"type\":\"none\",\"only_shiny\":true,\"selected\":[],\"linked\":false},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":1,\"duration\":300,\"default_on\":false},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":false,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n<br>\n\nDue to these low frequencies, I'm going to do the following;\n\n- `sat.taken`: drop\n- `HomelessIndicator`: drop\n- *`LimitedEnglishProficiency`*: drop\n- `ps.grad.InstitutionSector`: combine categories 3, 5, 6, 7, 8 and 9 into one category. This means that the following institution sectors will be relabeled as \"11\";\n  - 3 - Private for-profit, 4-year or above\n  - 5 - Private, not-for-profit 2-year\n  - 6 - Private for-profit, 2-year\n  - 7 - Public, less than 2-year\n  - 8 - Private not-for-profit less than 2-year\n  - 9 - Private for-profit, less-than 2-year\n- `hs.grad.year`: drop\n- `grad.year.covid`: drop\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaster.ind.qual.var <- ind.qual.var %>%\n  select(-PersonID, -sat.taken, -HomelessIndicator, -LimitedEnglishProficiencyIndicator, -hs.grad.year, -grad.year.covid) %>%\n  mutate(ps.grad.InstitutionSector = ifelse(ps.grad.InstitutionSector %in% c(\"3\", \"5\", \"6\", \"7\", \"8\", \"9\"), \"11\", as.character(ps.grad.InstitutionSector))) \n```\n:::\n\n\n<br>\n\n# MCA\n\nFor the MCA analysis, I'm going to group these variables together to make sure that they aren't explaining the same thing. The goal is to eliminate any variables that are essentially the same. This will help me make my model smaller when analyzing the pathways taken after graduating high school.\n\nHere are the groupings I'm going to use;\n\n- Demographics\n  - `Gender`\n  - `economic.status`\n  - `SpecialEdStatus`\n  - `RaceEthnicity`\n  - `english.learner`\n  - `non.english.home`\n- High school characteristics\n  - `Dem_Desc`\n  - `edr`\n- High school accomplishments\n  - `pseo.participant`\n  - `took.ACT`\n  - `ap.exam`\n  - `cte.achievement`\n- Post-secondary\n  - `attended.ps`\n  - `ps.grad`\n  - `ps.grad.InstitutionSector`\n  - `highest.cred.level`\n  - `ps.grad.location`\n\n<br>\n\n## Demographics\n\nBelow are the variables that are categorized as \"demographics\".\n\n- Demographics\n  - `Gender`\n  - `economic.status`\n  - `SpecialEdStatus`\n  - `RaceEthnicity`\n  - `english.learner`\n  - `non.english.home`\n\nWhen I initially did this analysis, the category \"Unknown\" in the RaceEthnicity variable was throwing off the analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemographics <- master.ind.qual.var %>%\n  select(Gender, economic.status, SpecialEdStatus, RaceEthnicity, english.learner, non.english.home)  %>%\n  filter(RaceEthnicity != \"Unknown\")\n\nkable(head(demographics))\n```\n\n::: {.cell-output-display}\n\n\n|Gender |economic.status |SpecialEdStatus |RaceEthnicity |english.learner |non.english.home |\n|:------|:---------------|:---------------|:-------------|:---------------|:----------------|\n|M      |1               |0               |Hispanic      |0               |1                |\n|F      |0               |0               |White         |0               |0                |\n|M      |1               |1               |Hispanic      |0               |0                |\n|F      |1               |0               |White         |0               |0                |\n|F      |0               |0               |White         |0               |0                |\n|M      |1               |0               |White         |0               |0                |\n\n\n:::\n\n```{.r .cell-code}\nkable(names(demographics))\n```\n\n::: {.cell-output-display}\n\n\n|x                |\n|:----------------|\n|Gender           |\n|economic.status  |\n|SpecialEdStatus  |\n|RaceEthnicity    |\n|english.learner  |\n|non.english.home |\n\n\n:::\n:::\n\n\n<br>\n\nAs expected, we have 41,580 individuals in the dataset.\n\n<br>\n\n### MCA analysis\n\n### Eigenvalues - Demographic Variables\n\n**Overview** The MCA on demographic variables produced 9 dimensions, collectively explaining 100% of the variance in the data.\n\n**Dimension Retention** Using the average eigenvalue threshold (1/k = 0.167), Dimensions 1-5 are recommended for retention, collectively explaining 74.6% of the total variance. Dimension 1 is clearly the strongest, explaining 27.8% of variance, with a notable drop-off to subsequent dimensions which each explain approximately 11%.\n\n**Notes** The relatively even spread of variance across Dimensions 2-5 suggests that demographic variation in this dataset is multidimensional, with no single dominant second axis of variation.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemographics.mca <- FactoMineR::MCA(demographics, graph = FALSE)\n\neig.val <- get_eigenvalue(demographics.mca)\n\neig.val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1  0.4174275         27.82850                    27.82850\nDim.2  0.1985924         13.23949                    41.06799\nDim.3  0.1705803         11.37202                    52.44001\nDim.4  0.1670065         11.13377                    63.57378\nDim.5  0.1660384         11.06923                    74.64301\n```\n\n\n:::\n:::\n\n\n<br>\n\n#### COS2 - Demographic Variables\n\n**Overview** COS2 measures the quality of representation of each variable category across the five retained dimensions. Values closer to 1 indicate that a category is well represented in the retained dimensional space.\n\n**Well Represented Categories** Race/ethnicity categories are the best represented across the five dimensions. Black (0.970), Asian/PI (0.930), Hispanic (0.827), and AI (0.829) all show very strong representation, indicating these categories are well captured by the retained dimensions. The language variables non.english.home (0.823) and White (0.750) are also well represented.\n\n**Moderately Represented Categories** SpecialEdStatus (0.661), english.learner (0.647), and Gender (0.611) show moderate representation, suggesting some variation in these variables extends beyond the five retained dimensions.\n\n**Weakest Represented Categories** economic.status is the weakest represented variable at 0.437, suggesting that economic variation among students is not well captured by the five retained dimensions and may operate somewhat independently of other demographic factors.\n\n**Notes** The expected symmetry between binary category pairs (e.g., economic.status_0 and economic.status_1) is present throughout, confirming the technical integrity of the MCA results.\n\n\\<br\\>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- demographics.mca$var$cos2 %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`, `Dim 3`, `Dim 4`, `Dim 5`) %>%\n  mutate(total = `Dim 1` + `Dim 2` + `Dim 3` + `Dim 4` + `Dim 5`) \n  \ndatatable(table) %>%\n  formatCurrency(1:6, \"\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3a2bcd7e0f8dd17caf83\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3a2bcd7e0f8dd17caf83\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"F\",\"M\",\"economic.status_0\",\"economic.status_1\",\"SpecialEdStatus_0\",\"SpecialEdStatus_1\",\"AI\",\"Asian/PI\",\"Black\",\"Hispanic\",\"White\",\"english.learner_0\",\"english.learner_1\",\"non.english.home_0\",\"non.english.home_1\"],[0.0006433197058525428,0.0006433197058548093,0.3381142360255754,0.3381142360254191,0.06698103409207813,0.06698103409194182,0.0002974856968582639,0.1347892900334977,0.07354094421984392,0.4658618110008125,0.6675301443064846,0.6232472239127097,0.623247223913389,0.7475903690877105,0.747590369089051],[0.2730389045741674,0.2730389045742881,0.04105120138265646,0.04105120138270818,0.5749801493522569,0.5749801493527599,0.08694314817563122,0.1171432533989965,0.003302030358492623,0.01265178316761024,0.01589769856727827,0.01367207162629994,0.01367207162630063,0.07225704776042349,0.07225704776050931],[0.2778233707363877,0.2778233707362279,0.05024050987262223,0.05024050987263003,0.0009824469338506401,0.0009824469338539543,0.5231671096596802,0.05974296639984412,0.06620739999026302,0.04292215444107314,0.03492092363772339,0.009261335813184909,0.009261335813187678,0.002341762965702856,0.002341762965704035],[0.003764156320819967,0.003764156320823147,0.002535025571719546,0.002535025571713995,0.005601671734633717,0.005601671734633314,0.1839017304231494,0.1824376180082223,0.3695728048271394,0.2863495816805245,0.03494802130714339,0.0001955524433715854,0.0001955524433715486,0.0008962692942875431,0.0008962692942878542],[0.04682377414590148,0.04682377414594202,0.005574185622704521,0.005574185622700433,0.01287181914566154,0.01287181914566391,0.04366425789245722,0.4347601614220017,0.4576313402506305,0.01817520643586058,0.0001191301043932374,0.0006212390594070522,0.0006212390594092515,0.0002428237663990053,0.0002428237663992523],[0.602093525483129,0.6020935254831359,0.4375151584752781,0.4375151584751718,0.6614171212584808,0.6614171212588529,0.8379737318477762,0.9288732892625622,0.9702545196463694,0.825960536725881,0.7534159179230229,0.6469974228549731,0.6469974228556581,0.8233282728745235,0.8233282728759515]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n      <th>Dim 3<\\/th>\\n      <th>Dim 4<\\/th>\\n      <th>Dim 5<\\/th>\\n      <th>total<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2},{\"name\":\"Dim 3\",\"targets\":3},{\"name\":\"Dim 4\",\"targets\":4},{\"name\":\"Dim 5\",\"targets\":5},{\"name\":\"total\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\",\"options.columnDefs.5.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n\n```{.r .cell-code}\nfviz_cos2(demographics.mca, choice = \"var\", axes = 1:5)\n```\n\n::: {.cell-output-display}\n![](analysis_mca_files/figure-html/demogrpahics mca correlation between variables-2.png){width=672}\n:::\n:::\n\n\n<br>\n\n#### Contributions - Demographic Variables\n\n**Overview** Contributions measure how much each variable category drives each retained dimension. Categories with higher contributions are the primary drivers of that dimension's axis of variation.\n\n**Dimension 1 - English Language Learner / Hispanic Axis** Dimension 1 is primarily driven by non.english.home_1 (27.2%), english.learner_1 (22.7%), and Hispanic (17.1%), indicating this axis captures variation among students who speak a non-English language at home, are English language learners, and are of Hispanic ethnicity. These three categories together account for over 67% of Dimension 1.\n\n**Dimension 2 - Special Education / Gender Axis** Dimension 2 is dominated by SpecialEdStatus_1 (41.6%), with secondary contributions from Gender (F: 11.4%, M: 11.1%), suggesting this axis captures variation among students with special education status alongside an independent gender gradient.\n\n**Dimension 3 - American Indian / Gender Axis** Dimension 3 is primarily driven by AI (48.9%) with notable secondary contributions from Gender (F: 14.3%, M: 14.0%), suggesting this axis captures variation unique to American Indian students alongside a gender gradient.\n\n**Dimension 4 - Multi-Minority Race/Ethnicity Axis** Dimension 4 is shared across Black (33.8%), Hispanic (26.7%), and Asian/PI (19.1%) and AI (18.6%), suggesting this dimension captures a broader pattern of variation among minority race/ethnicity groups.\n\n**Dimension 5 - Black / Asian/PI Axis** Dimension 5 is primarily driven by Black (46.6%) and Asian/PI (41.5%), suggesting this dimension captures residual variation that distinguishes these two groups from other minority race/ethnicity categories.\n\n**Notes** The removal of unknown race/ethnicity individuals has produced a notably cleaner dimensional structure, particularly for Dimensions 3-5 which now tell a more interpretable story of variation among specific minority race/ethnicity groups.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- demographics.mca$var$contrib %>%\n  as.data.frame() %>%\n  mutate(id = seq(n())) %>%\n  select(id, `Dim 1`, `Dim 2`, `Dim 3`, `Dim 4`, `Dim 5`) %>%\n  mutate(`Dim 1` = `Dim 1` / 100,\n         `Dim 2` = `Dim 2` / 100,\n         `Dim 3` = `Dim 3` / 100,\n         `Dim 4` = `Dim 4` / 100,\n         `Dim 5` = `Dim 5` / 100)\n\ndatatable(table) %>%\n  formatPercentage(2:6, digits = 1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-6d33106123076d15f35a\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6d33106123076d15f35a\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"F\",\"M\",\"economic.status_0\",\"economic.status_1\",\"SpecialEdStatus_0\",\"SpecialEdStatus_1\",\"AI\",\"Asian/PI\",\"Black\",\"Hispanic\",\"White\",\"english.learner_0\",\"english.learner_1\",\"non.english.home_0\",\"non.english.home_1\"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],[0.0001301529349856312,0.0001267059115050569,0.05018800677115072,0.08481117304150726,0.003630128858278996,0.02311344979638028,0.0001170234340959887,0.0522487382469224,0.02875968644140168,0.1713232852167856,0.03821607162341906,0.02215541836616759,0.2266890699281087,0.02625257128528187,0.2722385181440093],[0.1161101436485804,0.1130350351880679,0.01280798707834777,0.02164382445730881,0.06550003962912941,0.4170463189427784,0.07188869977527707,0.09544566780777167,0.002714279240135968,0.00977979026917877,0.001913057114789277,0.0010215801499527,0.01045256967041482,0.005333433446424149,0.05530757358184384],[0.1375460668008291,0.133903240597587,0.01824915743940399,0.03083869133343686,0.0001302961500206531,0.0008296106391132489,0.5036159433734303,0.05667081946366866,0.0633597954980348,0.03862718720964023,0.004892301013462907,0.000805648351947202,0.00824320590897836,0.0002012349316540335,0.002086801288792167],[0.001903453780788682,0.001853041933541927,0.0009405164791564398,0.001589349946207462,0.0007588141519851234,0.004831457364585235,0.1808173659031458,0.1767593469178733,0.3612455656514932,0.2632106209091545,0.005000867240706849,1.737522443181654e-05,0.000177779241228426,7.866729918471136e-05,0.0008157779565163205],[0.02381584214465947,0.02318509365558872,0.002080129309754169,0.003515146709106476,0.001753809983046841,0.01116671076377482,0.04318224804176902,0.4236845019586991,0.4499281018690294,0.01680393723713456,1.714624786990245e-05,5.552016799337698e-05,0.0005680694012044012,2.143738240550179e-05,0.0002223051279638903]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>id<\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n      <th>Dim 3<\\/th>\\n      <th>Dim 4<\\/th>\\n      <th>Dim 5<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":5,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":6,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"id\",\"targets\":1},{\"name\":\"Dim 1\",\"targets\":2},{\"name\":\"Dim 2\",\"targets\":3},{\"name\":\"Dim 3\",\"targets\":4},{\"name\":\"Dim 4\",\"targets\":5},{\"name\":\"Dim 5\",\"targets\":6}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\",\"options.columnDefs.4.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n<br>\n\n#### Summary - Demographic Variables\n\nMultiple Correspondence Analysis on the demographic variables produced five retained dimensions explaining 74.6% of the total variance. Dimension 1 captured an English language learner / Hispanic axis, driven by non.english.home, english.learner, and Hispanic ethnicity. Dimension 2 captured a special education / gender axis, Dimension 3 an American Indian / gender axis, and Dimensions 4 and 5 captured variation among minority race/ethnicity groups.\n\nOverall, the MCA revealed that most demographic variables are capturing distinct and meaningful axes of variation, with the exception of some expected overlap between the language variables and Hispanic ethnicity. Given that this overlap is conceptually expected in a Southwest Minnesota context and that each variable retains some independent information, no demographic variables were eliminated following MCA.\n\nVariables to eliminate:\n\n- None\n\n<br>\n\n## High school characteristics\n\nBelow are the variables that are categorized as \"high school characteristics\".\n\n- High school characteristics\n  - `Dem_Desc`\n  - `edr`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhs.char <- master.ind.qual.var %>%\n  select(Dem_Desc, edr) \n\nkable(head(hs.char))\n```\n\n::: {.cell-output-display}\n\n\n|Dem_Desc             |edr                            |\n|:--------------------|:------------------------------|\n|Town/rural mix       |EDR 8 - Southwest              |\n|Urban/town/rural mix |EDR 6E- Southwest Central      |\n|Town/rural mix       |EDR 6W- Upper Minnesota Valley |\n|Town/rural mix       |EDR 6W- Upper Minnesota Valley |\n|Town/rural mix       |EDR 6W- Upper Minnesota Valley |\n|Entirely rural       |EDR 8 - Southwest              |\n\n\n:::\n\n```{.r .cell-code}\nkable(names(hs.char))\n```\n\n::: {.cell-output-display}\n\n\n|x        |\n|:--------|\n|Dem_Desc |\n|edr      |\n\n\n:::\n:::\n\n\n<br>\n\nWe have 50,830 individuals in the dataset.\n\n<br>\n\n### MCA analysis\n\n#### Eigenvalues - High School Characteristics\n\n**Overview** The MCA on high school characteristics variables produced 4 dimensions, collectively explaining 100% of the variance in the data.\n\n**Dimension Retention** Using the average eigenvalue threshold (1/k = 0.500), Dimensions 1-2 are recommended for retention, collectively explaining 63.0% of the total variance. Dimension 1 is the strongest, explaining 34.1% of variance, with Dimension 2 explaining an additional 28.9%.\n\n**Notes** The relatively balanced explanation of variance across Dimensions 1 and 2 suggests that the two geographic variables, Dem_Desc and edr, are capturing distinct but complementary axes of geographic variation in the dataset.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhs.char.mca <- FactoMineR::MCA(hs.char, graph = FALSE)\n\neig.val <- get_eigenvalue(hs.char.mca)\n\neig.val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1  0.6825636         34.12818                    34.12818\nDim.2  0.5800517         29.00258                    63.13076\nDim.3  0.4199483         20.99742                    84.12818\nDim.4  0.3174364         15.87182                   100.00000\n```\n\n\n:::\n:::\n\n\n<br>\n\n#### COS2 - High School Characteristics\n\n**Overview** COS2 measures the quality of representation of each variable category across the two retained dimensions. All categories show adequate representation with total COS2 values ranging from 0.588 to 0.681.\n\n**Dimension 1 - Urban/Southwest Central Axis** Urban/town/rural mix (0.671) and EDR 6E Southwest Central (0.629) load most strongly on Dimension 1, suggesting this axis captures variation associated with more urban and centrally located communities.\n\n**Dimension 2 - Rural/Southwest Axis** Entirely rural (0.527) and EDR 8 Southwest (0.461) load most strongly on Dimension 2, suggesting this axis captures variation associated with more rural and southwestern communities.\n\n**Notes** The clean separation of categories across the two dimensions, with Dem_Desc and edr categories each contributing to both dimensions, confirms that these two geographic variables are capturing distinct but complementary axes of geographic variation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- hs.char.mca$var$cos2 %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`) %>%\n  mutate(total = `Dim 1` + `Dim 2`)\n  \ndatatable(table) %>%\n  formatCurrency(1:3, digits = 3, \"\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-8306e0b72c578e10ec16\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8306e0b72c578e10ec16\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"Entirely rural\",\"Town/rural mix\",\"Urban/town/rural mix\",\"EDR 6E- Southwest Central\",\"EDR 6W- Upper Minnesota Valley\",\"EDR 8 - Southwest\"],[0.0614911766432899,0.2060562307878129,0.6706559107936931,0.6287883739820908,0.2541544465118437,0.1352656960800037],[0.5277956530660622,0.4049423349233548,0.01011930778014109,0.04569890099430676,0.3640678273623119,0.4651010789099966],[0.5892868297093521,0.6109985657111676,0.6807752185738343,0.6744872749763975,0.6182222738741555,0.6003667749900004]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n      <th>total<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2},{\"name\":\"total\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n\n```{.r .cell-code}\nfviz_cos2(hs.char.mca, choice = \"var\", axes = 1:2)\n```\n\n::: {.cell-output-display}\n![](analysis_mca_files/figure-html/hs characteristics mca correlation between variables-2.png){width=672}\n:::\n:::\n\n\n<br>\n\n#### Contributions - High School Characteristics\n\n**Overview** Contributions measure how much each variable category drives each retained dimension. Categories with higher contributions are the primary drivers of that dimension's axis of variation.\n\n**Dimension 1 - Urban/Southwest Central Axis** Dimension 1 is primarily driven by Urban/town/rural mix (41.7%) and EDR 6E Southwest Central (29.5%), with a secondary contribution from EDR 6W Upper Minnesota Valley (14.9%). This axis clearly captures variation associated with more urban communities concentrated in the Southwest Central region.\n\n**Dimension 2 - Rural/Southwest Axis** Dimension 2 is primarily driven by Entirely rural (39.1%), EDR 6W Upper Minnesota Valley (25.7%), and EDR 8 Southwest (21.9%), with a minor contribution from Town/rural mix (10.2%). This axis captures variation associated with more rural communities concentrated in the western and southwestern portions of the region.\n\n**Notes** The clean separation of contributions across the two dimensions confirms that Dim_Desc and edr are capturing distinct but complementary geographic axes of variation, with Dimension 1 reflecting an urban/central gradient and Dimension 2 reflecting a rural/peripheral gradient.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- hs.char.mca$var$contrib %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`) %>%\n  mutate(`Dim 1` = `Dim 1` / 100,\n         `Dim 2` = `Dim 2` / 100)\n\ndatatable(table) %>%\n  formatPercentage(1:2, digits = 1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-22d6a907c60dd776630d\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-22d6a907c60dd776630d\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"Entirely rural\",\"Town/rural mix\",\"Urban/town/rural mix\",\"EDR 6E- Southwest Central\",\"EDR 6W- Upper Minnesota Valley\",\"EDR 8 - Southwest\"],[0.03864698541731674,0.04421679131013436,0.4171362232733475,0.2946603829290195,0.1508274132668513,0.05451220380333061],[0.3903418007336125,0.1022518295832867,0.007406369684267833,0.02519993577959513,0.2542384926935983,0.2205615715256397]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n<br>\n\n#### Summary - High School Characteristics\n\nMultiple Correspondence Analysis on the high school characteristics variables produced two retained dimensions explaining 63.0% of the total variance. Dimension 1 captured an urban/Southwest Central axis, primarily driven by Urban/town/rural mix and EDR 6E Southwest Central, while Dimension 2 captured a rural/peripheral axis driven by Entirely rural, EDR 6W Upper Minnesota Valley, and EDR 8 Southwest. All category COS2 values were adequate, ranging from 0.588 to 0.681, indicating that both variables are well represented across the two retained dimensions.\n\nThe MCA revealed that Dem_Desc and edr are capturing distinct but complementary axes of geographic variation rather than redundant information. As a result, no high school characteristics variables were eliminated following MCA.\n\nVariables to drop;\n\n- None\n\n<br>\n\n## High school accomplishments\n\nBelow are the variables that are categorized as \"high school accomplishments\".\n\n- High school accomplishments\n  - `pseo.participant`\n  - `took.ACT`\n  - `ap.exam`\n  - `cte.achievement`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhs.accomplishments <- master.ind.qual.var %>%\n  select(pseo.participant, took.ACT, ap.exam, cte.achievement) %>%\n  filter(!is.na(pseo.participant))\n\nkable(head(hs.accomplishments))\n```\n\n::: {.cell-output-display}\n\n\n|pseo.participant |took.ACT |ap.exam |cte.achievement               |\n|:----------------|:--------|:-------|:-----------------------------|\n|0                |No       |0       |CTE Concentrator or Completor |\n|0                |Yes      |1       |No CTE                        |\n|0                |Yes      |0       |CTE Participant               |\n|1                |Yes      |0       |CTE Concentrator or Completor |\n|0                |Yes      |0       |CTE Concentrator or Completor |\n|0                |Yes      |1       |CTE Concentrator or Completor |\n\n\n:::\n\n```{.r .cell-code}\nkable(names(hs.accomplishments))\n```\n\n::: {.cell-output-display}\n\n\n|x                |\n|:----------------|\n|pseo.participant |\n|took.ACT         |\n|ap.exam          |\n|cte.achievement  |\n\n\n:::\n:::\n\n\n<br>\n\nThere are 40,543 individuals in the dataset.\n\n<br>\n\n#### Eigenvalues - High School Accomplishments\n\n**Overview** The MCA on high school accomplishment variables produced 5 dimensions, collectively explaining 100% of the variance in the data. Analysis is restricted to individuals with known PSEO participation status, excluding the 2008-2010 graduation cohorts where PSEO data was unavailable.\n\n**Dimension Retention** Using the average eigenvalue threshold (1/k = 0.250), Dimensions 1-2 are recommended for retention, collectively explaining 52.1% of the total variance. Dimension 1 is the strongest, explaining 31.8% of variance, with Dimension 2 explaining an additional 20.3%.\n\n**Notes** The relatively even spread of variance across Dimensions 3-5 suggests that additional axes of variation exist beyond the two retained dimensions, though none meet the threshold for retention.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhs.accomplishments.mca <- FactoMineR::MCA(hs.accomplishments, graph = FALSE)\n\neig.val <- get_eigenvalue(hs.accomplishments.mca)\n\neig.val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1  0.3973477         31.78782                    31.78782\nDim.2  0.2531020         20.24816                    52.03598\nDim.3  0.2477070         19.81656                    71.85254\nDim.4  0.2027354         16.21883                    88.07138\nDim.5  0.1491078         11.92862                   100.00000\n```\n\n\n:::\n:::\n\n\n<br>\n\n#### COS2 - High School Accomplishments\n\n**Overview** COS2 measures the quality of representation of each variable category across the two retained dimensions. Values range from 0.040 to 0.805, suggesting considerable variation in how well categories are represented in the retained dimensional space.\n\n**Well Represented Categories** No CTE is the best represented category (0.805), loading almost entirely on Dimension 2. took.ACT (0.649) and pseo.participant (0.592) are also well represented across the two dimensions.\n\n**Moderately Represented Categories** CTE Concentrator or Completor (0.538) and ap.exam (0.427) show moderate representation, suggesting some variation in these categories extends beyond the two retained dimensions.\n\n**Poorly Represented Categories** CTE Participant has a notably low total COS2 of 0.040, indicating this category is poorly captured by the two retained dimensions and may be operating independently of the other high school accomplishment variables.\n\n**Notes** The poor representation of CTE Participant warrants attention and may suggest that this intermediate category carries unique variation not shared with either No CTE or CTE Concentrator or Completor categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- hs.accomplishments.mca$var$cos2 %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`) %>%\n  mutate(total = `Dim 1` + `Dim 2`)\n  \ndatatable(table) %>%\n  formatCurrency(1:3, \"\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-00be1fb1b572fdd00ae1\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-00be1fb1b572fdd00ae1\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"pseo.participant_0\",\"pseo.participant_1\",\"No\",\"Yes\",\"ap.exam_0\",\"ap.exam_1\",\"CTE Concentrator or Completor\",\"CTE Participant\",\"No CTE\"],[0.5658066543177809,0.5658066543167721,0.5626948936609779,0.5626948936604809,0.3713998073439031,0.371399807343151,0.0894745332827027,0.03777087098111678,0.02172058326521254],[0.01686091498751467,0.01686091498748517,0.07150707039156075,0.07150707039152653,0.04407544338892454,0.04407544338881039,0.3352238816319363,0.03875807042121795,0.8635374410673562],[0.5826675693052955,0.5826675693042573,0.6342019640525387,0.6342019640520073,0.4154752507328277,0.4154752507319613,0.424698414914639,0.07652894140233474,0.8852580243325687]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n      <th>total<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2},{\"name\":\"total\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n\n```{.r .cell-code}\nfviz_cos2(hs.accomplishments.mca, choice = \"var\", axes = 1:2)\n```\n\n::: {.cell-output-display}\n![](analysis_mca_files/figure-html/high school accomplishments mca correlation between variables-2.png){width=672}\n:::\n:::\n\n\n<br>\n\n#### Contributions - High School Accomplishments\n\n**Overview** Contributions measure how much each variable category drives each retained dimension. Categories with higher contributions are the primary drivers of that dimension's axis of variation.\n\n**Dimension 1 - Academic Achievement / College Preparedness Axis** Dimension 1 is primarily driven by took.ACT No (23.8%), pseo.participant_1 (21.1%), and ap.exam_1 (20.0%), with a secondary contribution from took.ACT Yes (11.6%). This axis clearly captures variation associated with academic achievement and college preparedness behaviors in high school, distinguishing students who took the ACT, participated in PSEO, and took AP exams from those who did not.\n\n**Dimension 2 - CTE Participation Axis** Dimension 2 is overwhelmingly driven by No CTE (61.7%) and CTE Concentrator or Completor (22.3%), indicating this axis captures variation associated with CTE participation and achievement. The near-absence of CTE Participant (0.1%) on this dimension suggests that the intermediate CTE category is not meaningfully contributing to this axis of variation.\n\n**Notes** The very low contributions of CTE Participant across both dimensions, combined with its poor COS2 representation (0.040), raises the question of whether this intermediate category is adding meaningful information to the analysis. This warrants consideration when interpreting subsequent modeling results involving cte.achievement.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- hs.accomplishments.mca$var$contrib %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`) %>%\n  mutate(`Dim 1` = `Dim 1` / 100,\n         `Dim 2` = `Dim 2` / 100)\n\ndatatable(table) %>%\n  formatPercentage(1:2, digits = 1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-dc62099bb88340723307\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-dc62099bb88340723307\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"pseo.participant_0\",\"pseo.participant_1\",\"No\",\"Yes\",\"ap.exam_0\",\"ap.exam_1\",\"CTE Concentrator or Completor\",\"CTE Participant\",\"No CTE\"],[0.1472233813632045,0.2087662143069178,0.2394209331861959,0.1146108304057704,0.03550387528717616,0.1981704129865905,0.02895762961683311,0.01657755550192585,0.01076916734538609],[0.006887553926085135,0.009766713314621376,0.04776538326436701,0.02286529489183715,0.006614635406547761,0.03692061837384884,0.1703231395851995,0.02670550375107204,0.6721511574864223]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n<br>\n\n#### Summary - High School Accomplishments\n\nMultiple Correspondence Analysis on the high school accomplishment variables produced two retained dimensions explaining 52.1% of the total variance, restricted to individuals with known PSEO participation status. Dimension 1 captured a clear academic achievement and college preparedness axis, primarily driven by took.ACT, pseo.participant, and ap.exam, while Dimension 2 captured a CTE participation axis driven almost entirely by No CTE and CTE Concentrator or Completor.\n\nThe CTE Participant category showed consistently poor representation across both dimensions, with a total COS2 of 0.040 and minimal contributions to either dimension, suggesting this intermediate category carries unique variation not well captured by the retained dimensional structure. Despite this, cte.achievement was retained in its original form as the poor representation of CTE Participant may reflect genuine independence rather than redundancy, and collapsing or dropping the category would require further substantive justification. No high school accomplishment variables were eliminated following MCA.\n\nVariables to drop\n\n- None\n\n<br>\n\n## Post secondary\n\nBelow are the variables that are categorized as \"high school accomplishments\".\n\n- Post-secondary\n  - `attended.ps`\n  - `ps.grad`\n  - `ps.grad.InstitutionSector`\n  - `highest.cred.level`\n  - `ps.grad.location`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps <- master.ind.qual.var %>%\n  select(attended.ps, ps.grad, ps.grad.InstitutionSector, highest.cred.level, ps.grad.location)\n\nkable(head(ps))\n```\n\n::: {.cell-output-display}\n\n\n|attended.ps |ps.grad |ps.grad.InstitutionSector |highest.cred.level  |ps.grad.location    |\n|:-----------|:-------|:-------------------------|:-------------------|:-------------------|\n|Yes         |No      |Did not grad              |Did not graduate ps |Did not graduate ps |\n|Yes         |No      |Did not grad              |Did not graduate ps |Did not graduate ps |\n|Yes         |No      |Did not grad              |Did not graduate ps |Did not graduate ps |\n|Yes         |Y       |4                         |Associate degree    |PS grad MN          |\n|No          |No      |Never attended ps         |Did not graduate ps |Did not graduate ps |\n|Yes         |No      |Did not grad              |Did not graduate ps |Did not graduate ps |\n\n\n:::\n\n```{.r .cell-code}\nkable(names(ps))\n```\n\n::: {.cell-output-display}\n\n\n|x                         |\n|:-------------------------|\n|attended.ps               |\n|ps.grad                   |\n|ps.grad.InstitutionSector |\n|highest.cred.level        |\n|ps.grad.location          |\n\n\n:::\n:::\n\n\n<br>\n\nThere are 50,830 individuals in the dataset.\n\n<br>\n\n### MCA analysis\n\n#### Eigenvalues - Postsecondary Variables\n\n**Overview** The MCA on postsecondary variables produced 14 meaningful dimensions, collectively explaining 100% of the variance in the data. Dimensions 15-20 have effectively zero eigenvalues, reflecting expected linear dependencies among structurally related postsecondary variables.\n\n**Dimension Retention** Based on a combination of the average eigenvalue threshold (1/k = 0.200) and a clear elbow in the variance explained after Dimension 2, Dimensions 1-3 are recommended for retention, collectively explaining 52.9% of the total variance. Dimensions 1 and 2 are clearly dominant, explaining 22.5% and 20.0% respectively, with a notable drop to Dimension 3 at 10.4%.\n\n**Notes** The structural relationships among postsecondary variables, such as ps.grad, ps.grad.location, and highest.cred.level, likely account for the linear dependencies observed in the near-zero eigenvalue dimensions. The relatively complex eigenvalue structure reflects the richness of variation captured by this variable group.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nps.mca <- FactoMineR::MCA(ps, graph = FALSE)\n\neig.val <- get_eigenvalue(ps.mca)\n\neig.val\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      eigenvalue variance.percent cumulative.variance.percent\nDim.1  0.9063819        22.659547                    22.65955\nDim.2  0.7999194        19.997985                    42.65753\nDim.3  0.4148194        10.370484                    53.02802\nDim.4  0.2922932         7.307330                    60.33535\nDim.5  0.2589649         6.474123                    66.80947\n```\n\n\n:::\n:::\n\n\n<br>\n\n#### COS2 - Postsecondary Variables\n\n**Overview** COS2 measures the quality of representation of each variable category across the three retained dimensions. Values range considerably from 0.010 to 1.000, revealing both strong redundancy among some variables and poor representation of others.\n\n**Perfectly or Near-Perfectly Represented Categories** Several categories achieve near-perfect total COS2 values, including ps.grad Attending ps (0.998), ps.grad.InstitutionSector Attending ps (0.998), highest.cred.level Attending ps (0.998), and ps.grad.location Attending ps (0.998). Similarly, ps.grad No (0.970), highest.cred.level Did not graduate ps (0.970), and ps.grad.location Did not graduate ps (0.972) are nearly identical in their representation. These patterns strongly suggest that these categories are capturing the same underlying variation across multiple variables, indicating considerable redundancy among ps.grad, ps.grad.location, and highest.cred.level.\n\n**Well Represented Categories** ps.grad.InstitutionSector_4 (Public 2-year, 0.909), highest.cred.level Bachelor degree (0.767), and ps.grad.InstitutionSector Never attended ps (0.587) are well represented across the three retained dimensions.\n\n**Moderately Represented Categories** attended.ps (0.587), ps.grad.InstitutionSector_1 (Public 4-year, 0.562), highest.cred.level Associate degree (0.451), and ps.grad.location PS grad outside MN (0.289) show moderate representation, suggesting some variation in these categories extends beyond the three retained dimensions.\n\n**Poorly Represented Categories** Several categories show notably poor representation, including ps.grad.InstitutionSector_11 (Private other, 0.010), ps.grad.InstitutionSector_10 (Foreign institutions, 0.078), highest.cred.level Master degree or higher (0.099), and ps.grad.location PS grad region categories (0.170-0.188). These categories carry unique variation not well captured by the three retained dimensions.\n\n**Notes** The near-identical COS2 patterns across ps.grad, ps.grad.location, and highest.cred.level for the Attending ps and Did not graduate ps categories strongly suggest redundancy among these variables that warrants careful consideration in variable retention decisions.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- ps.mca$var$cos2 %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`, `Dim 3`) %>%\n  mutate(total = `Dim 1` + `Dim 2` + `Dim 3`)\n  \ndatatable(table) %>%\n  formatCurrency(1:4, \"\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-7380b1f79062f7219469\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-7380b1f79062f7219469\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"attended.ps_No\",\"attended.ps_Yes\",\"ps.grad_Attending ps\",\"ps.grad_No\",\"ps.grad_Y\",\"ps.grad.InstitutionSector_1\",\"ps.grad.InstitutionSector_10\",\"ps.grad.InstitutionSector_11\",\"ps.grad.InstitutionSector_2\",\"ps.grad.InstitutionSector_4\",\"ps.grad.InstitutionSector_Attending ps\",\"ps.grad.InstitutionSector_Did not grad\",\"ps.grad.InstitutionSector_Never attended ps\",\"highest.cred.level_Associate degree\",\"highest.cred.level_Attending ps\",\"highest.cred.level_Bachelor degree\",\"highest.cred.level_Did not graduate ps\",\"highest.cred.level_Less than Associate Degree\",\"highest.cred.level_Master degree or higher\",\"ps.grad.location_Attending ps\",\"ps.grad.location_Did not graduate ps\",\"ps.grad.location_PS grad MN\",\"ps.grad.location_PS grad outside MN\",\"ps.grad.location_PS grad region\",\"ps.grad.location_PS grad Region\"],[0.6190509651602156,0.619050965159925,0.05996203309437095,0.9706649535673558,0.7236146408760051,0.1856570405279642,0.03449406449754528,0.005657896134539223,0.05233796682714139,0.1611148082074323,0.05996203309431776,0.1421981601601652,0.6190509651604733,0.09402812728584219,0.05996203309434942,0.2550657308020512,0.9706649535673405,0.07036941944651072,0.02999046255607018,0.05996203309430222,0.972630625898423,0.1632198334524642,0.1448806075421375,0.06281154802314758,0.05995012773031463],[5.560888999874286e-06,5.560889000002966e-06,0.938418583328374,1.887476075106924e-05,0.2539872541898046,0.06469416140457408,0.01202041975369383,0.001975069887851431,0.01824245150915496,0.05627809593850486,0.938418583328376,3.69586389572458e-06,5.560888999881227e-06,0.03315020957916009,0.9384185833283747,0.08918433361675397,1.887476075106857e-05,0.02488334200895498,0.01048145756805981,0.9384185833283756,1.268867601779102e-05,0.05691896661148291,0.05051184152140836,0.02192235822067964,0.02092289548159664],[1.736318037310305e-06,1.736318037127323e-06,1.282879373187029e-08,2.695863255870257e-06,2.464005503702147e-06,0.3063924207873957,0.02881172662786167,0.001908596845586504,0.07027475683315257,0.6904943114628304,1.282879372025443e-08,4.75873479516601e-06,1.73631803710615e-06,0.3248648117133965,1.28287937271607e-08,0.4191771614402762,2.695863255858798e-06,0.2746982380346082,0.05643058573558033,1.282879371687164e-08,2.509106707803629e-07,0.01779499980271917,0.08790697705209909,0.08047650822257116,0.1046366454336827],[0.6190582623672528,0.6190582623669622,0.9983806292515387,0.9706865241913627,0.9776043590713135,0.5567436227199339,0.07532621087910078,0.009541562867977157,0.1408551751694489,0.9078872156087676,0.9983806292514875,0.1422066147588561,0.6190582623675103,0.4520431485783988,0.9983806292515178,0.7634272258590814,0.9706865241913474,0.3699509994900739,0.09690250585971033,0.9983806292514715,0.9726435654851115,0.2379337998666663,0.283299426115645,0.1652104144663984,0.185509668645594]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n      <th>Dim 3<\\/th>\\n      <th>total<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"targets\":4,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatCurrency(data, \\\"\\\", 3, 3, \\\",\\\", \\\".\\\", true, null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3,4]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2},{\"name\":\"Dim 3\",\"targets\":3},{\"name\":\"total\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\",\"options.columnDefs.3.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n\n```{.r .cell-code}\nfviz_cos2(ps.mca, choice = \"var\", axes = 1:3)\n```\n\n::: {.cell-output-display}\n![](analysis_mca_files/figure-html/ps mca correlation between variables-2.png){width=672}\n:::\n:::\n\n\n<br>\n\n#### MCA Contributions - Postsecondary Variables\n\n**Overview** Contributions measure how much each variable category drives each retained dimension. Categories with higher contributions are the primary drivers of that dimension's axis of variation. The contribution results reveal striking redundancy among several postsecondary variables, with near-identical contributions appearing across multiple variables for the same underlying construct.\n\n**Dimension 1 - Did Not Graduate Postsecondary Axis** Dimension 1 is driven by near-identical contributions from attended.ps No (9.5%), ps.grad No (11.5%), highest.cred.level Did not graduate ps (11.5%), and ps.grad.location Did not graduate ps (11.5%). The near-identical contributions of these categories across four separate variables strongly indicates that these variables are capturing the same underlying construct — whether an individual did not attend or graduate from postsecondary education.\n\n**Dimension 2 - Currently Attending Postsecondary Axis** Dimension 2 is almost entirely driven by four identical contributions of 21.8% each from ps.grad Attending ps, ps.grad.InstitutionSector Attending ps, highest.cred.level Attending ps, and ps.grad.location Attending ps. This perfect replication of contributions across four variables is unambiguous evidence of redundancy, as all four variables are capturing exactly the same information about individuals currently attending postsecondary education.\n\n**Dimension 3 - Institution Type and Credential Level Axis** Dimension 3 is driven by ps.grad.InstitutionSector_4 (Public 2-year, 27.3%), highest.cred.level Bachelor degree (15.2%), highest.cred.level Less than Associate Degree (12.1%), and highest.cred.level Associate degree (13.7%). This dimension captures meaningful variation in the type of institution attended and the level of credential attained, representing the most substantively informative axis of variation among the postsecondary variables.\n\n**Notes** The contribution results provide compelling evidence of redundancy among ps.grad, ps.grad.location, highest.cred.level, and attended.ps, particularly for the Attending ps and Did not graduate ps categories which contribute identically across multiple variables. This redundancy warrants serious consideration of variable elimination prior to modeling, with Dimension 3 suggesting that institution type and credential level may be the most informative non-redundant postsecondary variables.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable <- ps.mca$var$contrib %>%\n  as.data.frame() %>%\n  select(`Dim 1`, `Dim 2`, `Dim 3`) %>%\n  mutate(`Dim 1` = `Dim 1` / 100,\n         `Dim 2` = `Dim 2` /100,\n         `Dim 3` = `Dim 3` / 100)\n\ndatatable(table) %>%\n  formatPercentage(1:3, digits = 1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-572f10f5a2a96ee8b70e\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-572f10f5a2a96ee8b70e\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"attended.ps_No\",\"attended.ps_Yes\",\"ps.grad_Attending ps\",\"ps.grad_No\",\"ps.grad_Y\",\"ps.grad.InstitutionSector_1\",\"ps.grad.InstitutionSector_10\",\"ps.grad.InstitutionSector_11\",\"ps.grad.InstitutionSector_2\",\"ps.grad.InstitutionSector_4\",\"ps.grad.InstitutionSector_Attending ps\",\"ps.grad.InstitutionSector_Did not grad\",\"ps.grad.InstitutionSector_Never attended ps\",\"highest.cred.level_Associate degree\",\"highest.cred.level_Attending ps\",\"highest.cred.level_Bachelor degree\",\"highest.cred.level_Did not graduate ps\",\"highest.cred.level_Less than Associate Degree\",\"highest.cred.level_Master degree or higher\",\"ps.grad.location_Attending ps\",\"ps.grad.location_Did not graduate ps\",\"ps.grad.location_PS grad MN\",\"ps.grad.location_PS grad outside MN\",\"ps.grad.location_PS grad region\",\"ps.grad.location_PS grad Region\"],[0.1007973175635825,0.03580094552047913,0.01228332057189653,0.1210060487437839,0.080900405615407,0.03285067222561555,0.007277301471785249,0.00123909953791725,0.01079649536482616,0.02925297706419476,0.01228332057188563,0.02590230836106677,0.1007973175636244,0.0184034038117576,0.01228332057189211,0.04196526650528273,0.121006048743782,0.0141702958171378,0.00636257701378706,0.01228332057188244,0.1209217579260501,0.0295820367701665,0.026797857287,0.01278797392073401,0.01224861088446299],[1.025963210919114e-06,3.64399112087768e-07,0.2178216422568291,2.666147535072781e-06,0.03217512692974198,0.01297068515340016,0.002873496159760085,0.0004901157786530714,0.004263970070780844,0.01157814541076076,0.2178216422568296,7.628259411881209e-07,1.025963210920394e-06,0.007351765393598679,0.2178216422568293,0.01662614011189695,2.666147535072687e-06,0.005677650425844402,0.002519628781810268,0.2178216422568294,1.787466094052556e-06,0.01168899414175156,0.01058639283470856,0.00505725097865928,0.004843769888677873],[6.177376049049729e-07,2.19406536517041e-07,5.742188595075285e-09,7.34324102778756e-07,6.019178472868989e-07,0.1184576326338809,0.01328151063160023,0.0009133087522807512,0.03167506391933183,0.2739346126511005,5.742188589876009e-09,1.894035817445291e-06,6.177376048323396e-07,0.1389297438484323,5.742188592967265e-09,0.1506911260250787,7.34324102775635e-07,0.1208656844350476,0.0261587290543816,5.742188588361866e-09,6.815972611931306e-08,0.007047017063459918,0.03552755746786506,0.03580004421014164,0.04671245869530056]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Dim 1<\\/th>\\n      <th>Dim 2<\\/th>\\n      <th>Dim 3<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"targets\":1,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":2,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"targets\":3,\"render\":\"function(data, type, row, meta) {\\n    return type !== 'display' ? data : DTWidget.formatPercentage(data, 1, 3, \\\",\\\", \\\".\\\", null);\\n  }\"},{\"className\":\"dt-right\",\"targets\":[1,2,3]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Dim 1\",\"targets\":1},{\"name\":\"Dim 2\",\"targets\":2},{\"name\":\"Dim 3\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false},\"selection\":{\"mode\":\"multiple\",\"selected\":null,\"target\":\"row\",\"selectable\":null}},\"evals\":[\"options.columnDefs.0.render\",\"options.columnDefs.1.render\",\"options.columnDefs.2.render\"],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n<br>\n\n#### MCA Summary - Postsecondary Variables\n\nMultiple Correspondence Analysis on the postsecondary variables produced three retained dimensions explaining 52.9% of the total variance. Dimension 1 captured a did not graduate postsecondary axis, driven by near-identical contributions from attended.ps, ps.grad, highest.cred.level, and ps.grad.location, all reflecting whether an individual did not attend or complete postsecondary education. Dimension 2 captured a currently attending postsecondary axis, again driven by perfectly identical contributions across ps.grad, ps.grad.InstitutionSector, highest.cred.level, and ps.grad.location, providing unambiguous evidence of redundancy among these variables for this particular category. Dimension 3 captured a more substantively distinct axis of institution type and credential level, primarily driven by public 2-year institution attendance and varying credential levels.\n\nWhile the MCA revealed considerable redundancy among the postsecondary variables, all five variables were retained on substantive grounds. Each variable contributes meaningful and distinct information to the modeling context, particularly given the importance of credential level distinctions, geographic location of attendance, and institution type in understanding regional workforce participation outcomes.\n\n<br>\n\n# Variables to keep and eliminate\n\nMultiple Correspondence Analysis was conducted across four variable groups: demographic variables, high school characteristics, high school accomplishments, and postsecondary variables. The MCA did not identify any additional variables for elimination beyond the decisions already made during the initial frequency table review. The following changes were made prior to MCA:\n\n**Variables Dropped:**\n\n- `sat.taken` — near-zero variance with only 0.5% of individuals having taken the SAT\n- `HomelessIndicator` — very sparse positive cases\n- `LimitedEnglishProficiencyIndicator` — lower counts compared to english.learner and non.english.home\n- `grad.year.covid` — redundant recoding of hs.grad.year\n- `hs.grad.year` — removed along with grad.year.covid to eliminate the temporal dimension from MCA\n- `attended.ps.within.first.year.hsgrad` — subsumed by other postsecondary variables\n\n**Variables Recoded:**\n\n- ps.grad.InstitutionSector — sparse categories 3, 5, 6, 8, and 9 collapsed into a new category 11 (Private other)\n- RaceEthnicity — Unknown race/ethnicity individuals removed from the dataset prior to MCA\n\n**Data Decisions:**\n\n- pseo.participant NA values — identified as representing the 2008-2010 graduation cohorts where PSEO data was unavailable due to data system limitations. These individuals are retained in the master dataset but excluded from any analysis involving pseo.participant.\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmaster.final.after.mca <- master.original %>%\n  select(-sat.taken, -HomelessIndicator, -LimitedEnglishProficiencyIndicator, -grad.year.covid, -hs.grad.year, -attended.ps.within.first.year.hsgrad) %>%\n  mutate(ps.grad.InstitutionSector = ifelse(ps.grad.InstitutionSector %in% c(\"3\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\") | is.na(ps.grad.InstitutionSector), \"11\", ps.grad.InstitutionSector)) %>%\n  select(1:ps.grad.in.MN, ps.grad.location, mn.emp.record.hs.grad.year:ncol(.))\n\nnames(master.final.after.mca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] \"PersonID\"                                          \n  [2] \"K12OrganizationID\"                                 \n  [3] \"OrganizationName\"                                  \n  [4] \"county.name\"                                       \n  [5] \"countyfp\"                                          \n  [6] \"Dem_Desc\"                                          \n  [7] \"edr\"                                               \n  [8] \"planning.region\"                                   \n  [9] \"grad.year\"                                         \n [10] \"Gender\"                                            \n [11] \"economic.status\"                                   \n [12] \"pseo.participant\"                                  \n [13] \"SpecialEdStatus\"                                   \n [14] \"non.english.home\"                                  \n [15] \"RaceEthnicity\"                                     \n [16] \"n.years.attended\"                                  \n [17] \"ACTCompositeScore\"                                 \n [18] \"took.ACT\"                                          \n [19] \"ap.exam\"                                           \n [20] \"total.cte.courses.taken\"                           \n [21] \"ACTE.SPED\"                                         \n [22] \"Agriculture..Food..and.Natural.Resources\"          \n [23] \"Architecture...Construction\"                       \n [24] \"Arts..A.V.Technology...Communication\"              \n [25] \"Business..Management...Administrative\"             \n [26] \"Diversified\"                                       \n [27] \"Education...Training\"                              \n [28] \"Finance\"                                           \n [29] \"Government...Public.Administration\"                \n [30] \"Health.Science\"                                    \n [31] \"Hospitality...Tourism\"                             \n [32] \"Human.Services\"                                    \n [33] \"Information.Technology\"                            \n [34] \"Law..Public.Safety...Security\"                     \n [35] \"Manufacturing\"                                     \n [36] \"Marketing\"                                         \n [37] \"Program.Area..Diversified.\"                        \n [38] \"Science..Technology..Engineering....Mathematics\"   \n [39] \"STEM\"                                              \n [40] \"Transportation..Distribution...Logistics\"          \n [41] \"Work.Experience.Handicapped\"                       \n [42] \"Work.Experience.Handicapped..16.20..on.IEP.\"       \n [43] \"Work.Experience.Career.Exploration..age.14.15.on.I\"\n [44] \"Work.Experience.Disadvantaged\"                     \n [45] \"Youth.Apprenticeship\"                              \n [46] \"cte.achievement\"                                   \n [47] \"english.learner\"                                   \n [48] \"MCA.M\"                                             \n [49] \"MCA.R\"                                             \n [50] \"MCA.S\"                                             \n [51] \"attended.ps\"                                       \n [52] \"first.attend.ps\"                                   \n [53] \"attended.ps.first.year\"                            \n [54] \"attended.ps.years.hsgrad\"                          \n [55] \"n.institutions\"                                    \n [56] \"first.InstitutionSector\"                           \n [57] \"ps.sector.1\"                                       \n [58] \"ps.sector.2\"                                       \n [59] \"ps.sector.3\"                                       \n [60] \"ps.sector.4\"                                       \n [61] \"ps.sector.5\"                                       \n [62] \"ps.sector.6\"                                       \n [63] \"ps.sector.7\"                                       \n [64] \"ps.sector.8\"                                       \n [65] \"ps.sector.9\"                                       \n [66] \"ps.in.same.ruca\"                                   \n [67] \"ps.in.same.edr\"                                    \n [68] \"ps.in.same.pr\"                                     \n [69] \"ps.in.MN\"                                          \n [70] \"ps.attended.in.same.ruca\"                          \n [71] \"ps.attended.in.same.edr\"                           \n [72] \"ps.attended.in.same.pr\"                            \n [73] \"ps.attended.in.MN\"                                 \n [74] \"ps.grad\"                                           \n [75] \"min.ps.grad.year\"                                  \n [76] \"max.ps.grad.year\"                                  \n [77] \"years.between.grads\"                               \n [78] \"ps.grad.InstitutionSector\"                         \n [79] \"highest.cred.level\"                                \n [80] \"ps.grad.in.same.ruca\"                              \n [81] \"ps.grad.in.same.edr\"                               \n [82] \"ps.grad.in.same.pr\"                                \n [83] \"ps.grad.in.MN\"                                     \n [84] \"ps.grad.location\"                                  \n [85] \"mn.emp.record.hs.grad.year\"                        \n [86] \"mn.emp.record.hs.grad.year.2\"                      \n [87] \"mn.emp.record.hs.grad.year.7\"                      \n [88] \"meaningful.emp.hs.grad.year\"                       \n [89] \"meaningful.emp.hs.grad.year.2\"                     \n [90] \"meaningful.emp.hs.grad.year.7\"                     \n [91] \"hs.grad.year.county.match\"                         \n [92] \"hs.grad.year.2.county.match\"                       \n [93] \"hs.grad.year.7.county.match\"                       \n [94] \"hs.grad.year.edr.match\"                            \n [95] \"hs.grad.year.2.edr.match\"                          \n [96] \"hs.grad.year.7.edr.match\"                          \n [97] \"hs.grad.year.region.match\"                         \n [98] \"hs.grad.year.2.region.match\"                       \n [99] \"hs.grad.year.7.region.match\"                       \n[100] \"hs.grad.year.state.match\"                          \n[101] \"hs.grad.year.2.state.match\"                        \n[102] \"hs.grad.year.7.state.match\"                        \n[103] \"ind.match.hs.grad.year\"                            \n[104] \"ind.match.hs.grad.year.2\"                          \n[105] \"ind.match.hs.grad.year.7\"                          \n[106] \"avg.unemp.rate\"                                    \n[107] \"wages.3year.avg\"                                   \n[108] \"avg.wages.pct.state\"                               \n```\n\n\n:::\n\n```{.r .cell-code}\nwrite_csv(master.final.after.mca, \"Data/SLEDS/Masters/After analysis/Master-final-after-mca.csv\")\n```\n:::\n\n",
    "supporting": [
      "analysis_mca_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"site_libs/ggiraphjs-0.9.4/girafe.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/ggiraphjs-0.9.4/girafe.js\"></script>\n<script src=\"site_libs/girafe-binding-0.9.6/girafe.js\"></script>\n<link href=\"site_libs/liberation-sans-0.5.1/css/liberation-sans.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/liberation-serif-0.5.1/css/liberation-serif.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/liberation-mono-0.5.1/css/liberation-mono.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}