<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>The pathways – Pathways taken after high school - Southwest</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-158031087360bce0ff56dc785ce39e06.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Pathways taken after high school - Southwest</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Summary</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data-prep-and-summaries" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Data Prep and Summaries</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data-prep-and-summaries">    
        <li>
    <a class="dropdown-item" href="./k12enrollment.html">
 <span class="dropdown-text">K12Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./k12orgs.html">
 <span class="dropdown-text">K12Orgs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./act.html">
 <span class="dropdown-text">ACT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ap.html">
 <span class="dropdown-text">AP</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./cteenrollment.html">
 <span class="dropdown-text">CTEEnrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ctedemographics.html">
 <span class="dropdown-text">CTEDemographics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./assessments.html">
 <span class="dropdown-text">Assessments</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./sat.html">
 <span class="dropdown-text">SAT</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nscenrollment.html">
 <span class="dropdown-text">National Student Clearinghouse - Enrollment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nsccompletions.html">
 <span class="dropdown-text">National Student Clearinghouse - Completions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./employment.html">
 <span class="dropdown-text">Employment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./emp_states_each_year.html">
 <span class="dropdown-text">Employment states each year</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./unemployment.html">
 <span class="dropdown-text">Unemployment</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./avgwages.html">
 <span class="dropdown-text">Average wages</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-fa-gear" role="img">
</i> 
 <span class="menu-text">Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-analysis">    
        <li>
    <a class="dropdown-item" href="./analysis_mca.html">
 <span class="dropdown-text">Multiple Correspondence Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_dep_var_states.html">
 <span class="dropdown-text">Dependent Variable States</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_local_employment_ct.html">
 <span class="dropdown-text">Local Employment Cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_post_secondary_pathways_ct.html">
 <span class="dropdown-text">Post-secondary pathways cross-tabs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_multivariate_confirmation_analysis.html">
 <span class="dropdown-text">Multivariate Confirmation Analysis - Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_post_secondary_graduates.html">
 <span class="dropdown-text">Non-college graduates</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_non_college_deeper.html">
 <span class="dropdown-text">Further analysis on non-college grads</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_multivariate_confirmation_non_college_grads.html">
 <span class="dropdown-text">Multivariate Confirmation Analysis on non-college grads - Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./analysis_multivariate_confirmation_disconnection_persistence.html">
 <span class="dropdown-text">Multivariate Confirmation Analysis on Persistent Disconnection</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="./summary_pathways.html" aria-current="page"> 
<span class="menu-text">Summary of the three pathways</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-findings-paths-taken-by-high-school-graduates" id="toc-the-findings-paths-taken-by-high-school-graduates" class="nav-link active" data-scroll-target="#the-findings-paths-taken-by-high-school-graduates">The Findings: Paths Taken by High School Graduates</a></li>
  <li><a href="#getting-to-know-the-pathways" id="toc-getting-to-know-the-pathways" class="nav-link" data-scroll-target="#getting-to-know-the-pathways">Getting to Know the Pathways</a>
  <ul class="collapse">
  <li><a href="#pathway-1-the-college-completers-pathway" id="toc-pathway-1-the-college-completers-pathway" class="nav-link" data-scroll-target="#pathway-1-the-college-completers-pathway">Pathway 1: The College Completers’ Pathway</a>
  <ul class="collapse">
  <li><a href="#completing-college-is-highly-associated-with-sustained-labor-force-participation" id="toc-completing-college-is-highly-associated-with-sustained-labor-force-participation" class="nav-link" data-scroll-target="#completing-college-is-highly-associated-with-sustained-labor-force-participation">Completing college is highly associated with sustained labor force participation</a></li>
  <li><a href="#who-was-more-likely-to-complete-a-postsecondary-program" id="toc-who-was-more-likely-to-complete-a-postsecondary-program" class="nav-link" data-scroll-target="#who-was-more-likely-to-complete-a-postsecondary-program">Who was more likely to complete a postsecondary program?</a></li>
  <li><a href="#where-do-college-completers-participate-in-the-labor-force" id="toc-where-do-college-completers-participate-in-the-labor-force" class="nav-link" data-scroll-target="#where-do-college-completers-participate-in-the-labor-force">Where Do College Completers Participate in the Labor Force?</a></li>
  <li><a href="#what-high-school-experiences-were-associated-with-college-location" id="toc-what-high-school-experiences-were-associated-with-college-location" class="nav-link" data-scroll-target="#what-high-school-experiences-were-associated-with-college-location">What high school experiences were associated with college location?</a></li>
  </ul></li>
  <li><a href="#pathway-2-the-workforce-first-pathway" id="toc-pathway-2-the-workforce-first-pathway" class="nav-link" data-scroll-target="#pathway-2-the-workforce-first-pathway">Pathway 2: The Workforce-First Pathway</a>
  <ul class="collapse">
  <li><a href="#understanding-this-group" id="toc-understanding-this-group" class="nav-link" data-scroll-target="#understanding-this-group">Understanding this group</a></li>
  <li><a href="#who-was-more-likely-to-stay-connected-to-the-regional-workforce" id="toc-who-was-more-likely-to-stay-connected-to-the-regional-workforce" class="nav-link" data-scroll-target="#who-was-more-likely-to-stay-connected-to-the-regional-workforce">Who was more likely to stay connected to the regional workforce?</a></li>
  </ul></li>
  <li><a href="#pathway-3-the-disconnected-pathway" id="toc-pathway-3-the-disconnected-pathway" class="nav-link" data-scroll-target="#pathway-3-the-disconnected-pathway">Pathway 3: The Disconnected Pathway</a>
  <ul class="collapse">
  <li><a href="#size-of-this-group" id="toc-size-of-this-group" class="nav-link" data-scroll-target="#size-of-this-group">Size of this group</a></li>
  <li><a href="#persistently-disconnected" id="toc-persistently-disconnected" class="nav-link" data-scroll-target="#persistently-disconnected">Persistently Disconnected</a></li>
  <li><a href="#two-kinds-of-disconnection" id="toc-two-kinds-of-disconnection" class="nav-link" data-scroll-target="#two-kinds-of-disconnection">Two Kinds of Disconnection</a></li>
  <li><a href="#a-local-opportunity" id="toc-a-local-opportunity" class="nav-link" data-scroll-target="#a-local-opportunity">A Local Opportunity</a></li>
  <li><a href="#who-is-most-at-risk-of-disconnection" id="toc-who-is-most-at-risk-of-disconnection" class="nav-link" data-scroll-target="#who-is-most-at-risk-of-disconnection">Who is Most at Risk of Disconnection?</a></li>
  <li><a href="#disparities-compound-across-the-pipeline" id="toc-disparities-compound-across-the-pipeline" class="nav-link" data-scroll-target="#disparities-compound-across-the-pipeline">Disparities Compound Across the Pipeline</a></li>
  </ul></li>
  <li><a href="#what-offers-protection-against-disconnection" id="toc-what-offers-protection-against-disconnection" class="nav-link" data-scroll-target="#what-offers-protection-against-disconnection">What Offers Protection Against Disconnection?</a>
  <ul class="collapse">
  <li><a href="#protections-against-persistent-instability" id="toc-protections-against-persistent-instability" class="nav-link" data-scroll-target="#protections-against-persistent-instability">Protections Against Persistent Instability</a></li>
  <li><a href="#protections-against-persistent-no-mn-employment-record-status" id="toc-protections-against-persistent-no-mn-employment-record-status" class="nav-link" data-scroll-target="#protections-against-persistent-no-mn-employment-record-status">Protections Against Persistent No-MN-Employment-Record Status</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The pathways</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-findings-paths-taken-by-high-school-graduates" class="level1">
<h1>The Findings: Paths Taken by High School Graduates</h1>
<p>Southwest Minnesota high school graduates sort into a small number of distinct workforce trajectories over the years following graduation, and that sorting continues to shift for a full decade. Looking at the proportion of graduates in each workforce-participation category at three points in time — immediately after graduation, six years out, and eleven years out — shows a population still very much in motion long after the high school diploma is granted.</p>
<p>At <strong>graduation (Year 0)</strong>, most graduates (58.0%) are attending postsecondary education, with smaller shares already in meaningful employment in the county (5.0%), the broader region (1.6%), or elsewhere in Minnesota (1.4%). Roughly a quarter (23.8%) are not yet meaningfully employed and not attending postsecondary, and 10.2% have no Minnesota employment record at all.</p>
<p>By <strong>six years out</strong>, the picture has changed substantially. Postsecondary attendance has fallen to 11.8% as most students have either completed or left school. Meaningful employment has grown across all three geographies — 14.9% in the same county, 10.0% in the broader region (together, nearly 25% employed within Southwest Minnesota), and 20.6% elsewhere in Minnesota (bringing total meaningful in-state employment to roughly 45%, nearly half the cohort). The “not meaningful” category has fallen to 16.2%, but the share with no Minnesota employment record has more than doubled, to 26.5%.</p>
<p>By <strong>eleven years out</strong>, postsecondary attendance has effectively disappeared (~0%). Meaningful employment holds roughly steady — 14.3% county, 10.1% region, 23.4% elsewhere in Minnesota — while the share with no Minnesota employment record climbs to 37.1%, over a third of the entire graduating cohort. This is the single largest category at the ten-year mark: more graduates have disappeared from Minnesota’s employment data than are working anywhere in the state.</p>
<p>The clear takeaway: meaningful employment in Southwest Minnesota specifically peaks around six years after graduation at nearly 25% of the cohort, and continued attachment to the region holds fairly steady after that. But the share of graduates who simply vanish from Minnesota’s workforce data — whether through out-of-state migration, informal work, or genuine disengagement — grows continuously and becomes the dominant outcome for this population by the ten-year mark.</p>
<p><br></p>
</section>
<section id="getting-to-know-the-pathways" class="level1">
<h1>Getting to Know the Pathways</h1>
<p>Three broad pathways emerge from this data: a <strong>College Completers’ Pathway</strong>, a <strong>Workforce-First Pathway</strong>, and a <strong>Disconnected Pathway</strong>. Each is examined in turn below.</p>
<p><br></p>
<section id="pathway-1-the-college-completers-pathway" class="level2">
<h2 class="anchored" data-anchor-id="pathway-1-the-college-completers-pathway">Pathway 1: The College Completers’ Pathway</h2>
<section id="completing-college-is-highly-associated-with-sustained-labor-force-participation" class="level3">
<h3 class="anchored" data-anchor-id="completing-college-is-highly-associated-with-sustained-labor-force-participation">Completing college is highly associated with sustained labor force participation</h3>
<p>Among the 47,189 Southwest Minnesota high school graduates in this analysis, <strong>53.1% completed a postsecondary credential</strong>, while the remaining 46.9% either attended without completing (18.8%) or never attended postsecondary education at all (28.1%).</p>
<p>That completion premium shows up clearly in workforce outcomes. Looking at meaningful employment status five years after graduation — and setting aside those still attending postsecondary at that point, since they haven’t yet had the chance to show a settled outcome — <strong>57.9% of college completers</strong> had achieved sustained workforce participation (meaningful employment in the region or elsewhere in Minnesota), compared to <strong>42.8% of non-completers</strong>. Completing a postsecondary credential is associated with roughly a 15-percentage-point advantage in sustained labor force attachment five years after high school.</p>
<p><br></p>
</section>
<section id="who-was-more-likely-to-complete-a-postsecondary-program" class="level3">
<h3 class="anchored" data-anchor-id="who-was-more-likely-to-complete-a-postsecondary-program">Who was more likely to complete a postsecondary program?</h3>
<p>A full multivariate model confirms that postsecondary completion is driven by a genuinely different set of forces than the workforce-attachment outcomes examined elsewhere in this project — the demographic groups facing the steepest barriers to completing college are not the same groups facing the steepest barriers to staying in the regional workforce afterward.</p>
<p><strong>American Indian graduates face the largest and most persistent completion disparity</strong> of any group, even after accounting for high school context and accomplishments — a gap that shrinks somewhat once academic preparation is controlled for, but remains substantial. <strong>Hispanic graduates</strong> show a similarly large and persistent gap. <strong>Asian/PI graduates</strong> show a smaller, stable disadvantage. <strong>Black graduates, notably, show no significant completion disadvantage</strong> relative to White graduates — a sharp contrast with the workforce-attachment patterns discussed later in this report, where Black graduates face the single largest disparity of any group.</p>
<p><strong>Gender runs in the opposite direction from workforce attachment</strong>: women show substantially higher odds of completing a postsecondary credential than men — the reverse of the pattern for staying in the regional workforce, where women show <em>lower</em> odds. This is one of the clearest tensions in the entire pipeline: the same gender gap that favors women in completion works against them in regional retention afterward.</p>
<p><strong>Economic status and special education status are the two largest barriers to completion identified anywhere in this project.</strong> Economically disadvantaged graduates and special education students both face large, significant completion gaps that shrink meaningfully — but do not disappear — once high school accomplishments (ACT participation, PSEO, AP exams) are accounted for. This points to a critical policy distinction: for these groups, a substantial share of the completion gap traces back to differences in academic preparation and college-oriented accomplishments during high school, not to demographic disadvantage acting independently once those accomplishments are equal.</p>
<p>Academic engagement variables show large, consistent effects throughout: ACT participation, PSEO participation, and AP exam participation are all strongly associated with higher odds of completion, and the completion rate gaps between those who did and didn’t engage in these activities are stark — for example, ACT-takers complete at more than double the rate of non-takers, and PSEO participants complete at roughly twice the rate of non-participants.</p>
<p><br></p>
</section>
<section id="where-do-college-completers-participate-in-the-labor-force" class="level3">
<h3 class="anchored" data-anchor-id="where-do-college-completers-participate-in-the-labor-force">Where Do College Completers Participate in the Labor Force?</h3>
<p><strong>Proportion of college completers that complete college in the region vs.&nbsp;outside the region.</strong> Among the 24,998 Southwest Minnesota graduates who completed a postsecondary credential, only <strong>30.8% completed it within the region itself</strong>. The remaining <strong>69.2%</strong> completed elsewhere — 36.3% elsewhere in Minnesota and 32.9% entirely outside the state.</p>
<p>Both <strong>where</strong> a graduate completes their credential and <strong>what level</strong> of credential they earn are independently associated with whether they go on to sustain regional employment.</p>
<p><strong>Graduation location matters.</strong> Among college completers, those who completed their credential <strong>outside the region</strong> show meaningfully lower odds of sustained regional workforce participation than those who completed locally — roughly 13% lower odds, net of everything else in the model. This confirms, at the individual level, what the raw numbers already suggest: leaving the region for school is associated with a real, independent pull away from returning to work in it.</p>
<p><strong>Credential level matters even more.</strong> Completers whose highest credential is a <strong>bachelor’s degree or higher</strong> show substantially lower odds of sustained regional workforce participation than those with a sub-baccalaureate credential — roughly 31% lower odds, the larger of the two postsecondary effects. This mirrors a pattern that runs throughout this entire project: higher academic attainment is consistently associated with a pull away from the region, even as engagement with education more broadly (attending at all, taking the ACT, participating in CTE) tends to support staying.</p>
<p><br></p>
</section>
<section id="what-high-school-experiences-were-associated-with-college-location" class="level3">
<h3 class="anchored" data-anchor-id="what-high-school-experiences-were-associated-with-college-location">What high school experiences were associated with college location?</h3>
<p><strong>Characteristics associated with completing college located in the region.</strong> The single largest predictor of completing locally is a graduate’s home EDR: graduates from <strong>EDR 8–Southwest</strong> are dramatically more likely — more than three times more likely — to complete their credential within the region than graduates from EDR 6W–Upper Minnesota Valley, a direct confirmation of the postsecondary infrastructure gap identified earlier in this project (EDR 6W has meaningfully less local postsecondary capacity). Beyond geography, <strong>American Indian, Asian/PI, and Hispanic graduates</strong> are all substantially more likely to complete locally than White graduates — a genuinely different pattern from completion itself, where American Indian and Hispanic graduates faced the steepest barriers to completing <em>at all</em>. Among those who do complete, these same groups show a strong pull toward staying close to home for school. <strong>Women, economically disadvantaged graduates, and special education students</strong> also show a consistent pull toward completing locally.</p>
<p><strong>Characteristics associated with completing college located outside the region.</strong> The clearest predictor of leaving the region for school is academic achievement itself: graduates who took the <strong>ACT</strong>, and especially those who took <strong>AP exams</strong>, are considerably more likely to complete their credential outside the region — the same academic-preparation variables that predict completion in the first place also predict leaving to do it. <strong>Black graduates</strong> are the one racial/ethnic group that breaks from the pattern above: rather than showing the regional pull seen among American Indian, Asian/PI, and Hispanic completers, Black graduates show significantly <em>lower</em> odds of completing locally — a finding that connects directly to their persistent workforce-attachment disadvantage discussed later in this report, suggesting the disparity may begin with where the credential itself is earned. Graduates from <strong>EDR 6W</strong> are, unsurprisingly, the least likely to complete locally and the most likely to complete elsewhere in Minnesota, consistent with that region’s documented postsecondary infrastructure gap.</p>
<p><br></p>
</section>
</section>
<section id="pathway-2-the-workforce-first-pathway" class="level2">
<h2 class="anchored" data-anchor-id="pathway-2-the-workforce-first-pathway">Pathway 2: The Workforce-First Pathway</h2>
<p><strong>Percent that did not complete college: 46.9%</strong> of Southwest Minnesota high school graduates either attended postsecondary education without completing (18.8%) or never attended at all (28.1%).</p>
<p><br></p>
<section id="understanding-this-group" class="level3">
<h3 class="anchored" data-anchor-id="understanding-this-group">Understanding this group</h3>
<p>Five years after high school graduation, <strong>40.8% of non-college completers had achieved sustained workforce participation</strong> — meaningful employment either within the region (25.7%) or elsewhere in Minnesota (15.1%). This is meaningfully lower than the 57.9% sustained-attachment rate among college completers over the same window, confirming the completion premium described above, but it also shows that a substantial share of non-completers do go on to build stable working lives without a postsecondary credential.</p>
<p><br></p>
</section>
<section id="who-was-more-likely-to-stay-connected-to-the-regional-workforce" class="level3">
<h3 class="anchored" data-anchor-id="who-was-more-likely-to-stay-connected-to-the-regional-workforce">Who was more likely to stay connected to the regional workforce?</h3>
<p>A full multivariate model of sustained regional workforce attachment among non-completers — controlling for demographics, high school context, accomplishments, and whether they ever attempted postsecondary education — identifies a genuinely different set of drivers than the completion pipeline above.</p>
<p><strong>CTE engagement is the single most reliable positive lever identified for this population.</strong> Both the level of CTE achievement (Concentrator/Completor status) and the sheer number of CTE courses taken are strongly and independently associated with higher odds of sustained regional employment.</p>
<p><strong>Having attempted postsecondary education — even without finishing — carries a real, independent benefit.</strong> Non-completers who attended some postsecondary education show substantially higher odds of sustained regional workforce attachment than those who never attended at all, even years after that attempt.</p>
<p><strong>Local wage competitiveness and community context matter more here than for the broader population.</strong> Non-completers from areas with higher local wages, and from EDR 6E specifically, show meaningfully better regional attachment outcomes.</p>
<p><strong>Demographic disparities persist but differ from the completion pipeline.</strong> Women show consistently lower odds of sustained regional employment than men among non-completers — the same direction seen for completers, reinforcing that this gender gap in regional retention is not explained by educational attainment. American Indian and Black graduates both show real, independent disadvantages in regional workforce attachment among non-completers.</p>
<p><strong>Academic achievement continues to show its familiar double edge.</strong> Having taken the ACT is itself associated with better regional attachment (engagement helps), but AP exam participation is associated with <em>worse</em> regional attachment — the same tension between academic engagement and academic achievement documented throughout this entire project, now visible even among students who never completed a postsecondary credential.</p>
<p><br></p>
</section>
</section>
<section id="pathway-3-the-disconnected-pathway" class="level2">
<h2 class="anchored" data-anchor-id="pathway-3-the-disconnected-pathway">Pathway 3: The Disconnected Pathway</h2>
<section id="size-of-this-group" class="level3">
<h3 class="anchored" data-anchor-id="size-of-this-group">Size of this group</h3>
<p>Five years after high school graduation, <strong>54.6% of non-college completers</strong> were either not meaningfully employed (23.9%) or had no Minnesota employment record at all (30.7%) — meaning that among graduates who don’t complete college, disconnection from sustained work is, at the five-year mark, actually more common than sustained attachment.</p>
<p><br></p>
</section>
<section id="persistently-disconnected" class="level3">
<h3 class="anchored" data-anchor-id="persistently-disconnected">Persistently Disconnected</h3>
<p>Looking at the full five-year trajectory rather than a single point in time, <strong>50.4% of non-college completers were persistently disconnected</strong> — meaning they experienced non-sustained employment or no Minnesota employment record in four or five of their first five years post-education. An additional 11.3% were broadly disconnected (three of five years), 24.3% were intermittently disconnected (one or two years), and only <strong>14.0% were consistently attached</strong> to the workforce in every one of the five years examined.</p>
<p>Persistent disconnection is the modal — not the exceptional — outcome for this population.</p>
<p><br></p>
</section>
<section id="two-kinds-of-disconnection" class="level3">
<h3 class="anchored" data-anchor-id="two-kinds-of-disconnection">Two Kinds of Disconnection</h3>
<p>Breaking the annual workforce state distribution down year by year reveals that “disconnection” isn’t one phenomenon — it’s two, moving in different directions over time.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>Sustained WF – Region</th>
<th>Sustained WF – MN</th>
<th>Non-sustained (in-region)</th>
<th>Non-sustained (out-region)</th>
<th>Non-sustained (unclassified)</th>
<th>Non-sustained (mixed)</th>
<th>No MN Emp Record</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Year 1</td>
<td>22.3%</td>
<td>9.9%</td>
<td>19.7%</td>
<td>7.8%</td>
<td>0.4%</td>
<td>11.2%</td>
<td>28.8%</td>
</tr>
<tr class="even">
<td>Year 2</td>
<td>24.8%</td>
<td>11.4%</td>
<td>16.1%</td>
<td>7.7%</td>
<td>0.3%</td>
<td>9.0%</td>
<td>30.6%</td>
</tr>
<tr class="odd">
<td>Year 3</td>
<td>26.0%</td>
<td>13.0%</td>
<td>13.6%</td>
<td>7.6%</td>
<td>0.3%</td>
<td>7.6%</td>
<td>32.0%</td>
</tr>
<tr class="even">
<td>Year 4</td>
<td>26.4%</td>
<td>14.4%</td>
<td>12.2%</td>
<td>7.3%</td>
<td>0.3%</td>
<td>6.1%</td>
<td>33.4%</td>
</tr>
<tr class="odd">
<td>Year 5</td>
<td>26.5%</td>
<td>15.6%</td>
<td>10.8%</td>
<td>7.0%</td>
<td>0.2%</td>
<td>5.0%</td>
<td>34.9%</td>
</tr>
</tbody>
</table>
<p>Sustained workforce participation does grow — from 32.1% in Year 1 to 42.0% by Year 5 — but no-MN-employment-record status grows just as steadily, from 28.8% to 34.9%, and is the single largest category in every year. Meanwhile, every form of non-sustained (unstable, but present) employment shrinks steadily over the same five years. The population isn’t simply stabilizing — it’s diverging into two groups: one consolidating into sustained work, and a separate, growing group disappearing from Minnesota’s workforce data entirely.</p>
<p><br></p>
</section>
<section id="a-local-opportunity" class="level3">
<h3 class="anchored" data-anchor-id="a-local-opportunity">A Local Opportunity</h3>
<p>Even when non-college completers experience non-sustained (unstable) employment rather than a MN-record-absence, that work is disproportionately happening close to home, not elsewhere. In Year 5, of the non-completers whose non-sustained employment could be clearly classified by location, <strong>roughly 61% was located within the region</strong>, compared to roughly 39% located outside the region — and this in-region share is actually higher than it was in Year 1. Unstable employment among non-completers is, more often than not, still local employment. This is a meaningful opportunity: these are graduates already working in Southwest Minnesota, just not yet in a sustained capacity — a fundamentally different, and arguably more addressable, challenge than recruiting workers back from elsewhere.</p>
<p><br></p>
</section>
<section id="who-is-most-at-risk-of-disconnection" class="level3">
<h3 class="anchored" data-anchor-id="who-is-most-at-risk-of-disconnection">Who is Most at Risk of Disconnection?</h3>
<p>Separating the two forms of disconnection — persistent non-sustained employment (job instability) and persistent no-MN-employment-record status (disappearance from the system) — and testing each in a full multivariate model reveals that they have almost entirely different risk profiles.</p>
<p><strong>Characteristics associated with persistent non-sustained employment (job instability):</strong> - <strong>Women</strong> show substantially higher odds of persistent job instability than men. - <strong>Special education status</strong> is one of the strongest and most stable predictors of instability, and its association strengthens — not weakens — once academic accomplishments are controlled for. - <strong>Economic disadvantage</strong> is significantly associated with higher odds of instability. - <strong>Black graduates</strong> show the single largest and most durable racial/ethnic disparity for this outcome, strengthening across every stage of the model. - Graduates from a <strong>town/rural mix</strong> community background show modestly elevated risk relative to entirely rural graduates.</p>
<p><strong>Characteristics associated with persistent no-Minnesota-employment-record status (disappearing from the system):</strong> - <strong>American Indian, Asian/PI, and Hispanic graduates</strong> all show significant, elevated risk — a genuinely different racial/ethnic pattern than job instability, where these same groups showed no elevated risk at all. - <strong>English learner status</strong> is a significant risk factor here, and only here — it shows no relationship to job instability. - <strong>Graduates from EDR 8</strong> show elevated risk of disappearing from Minnesota’s workforce record, even though — as shown above — they showed <em>lower</em> risk of job instability. EDR 8’s overall disadvantage is a records-absence story, not an instability story. - Higher <strong>ACT composite scores</strong> among test-takers are associated with greater risk of disappearing from the record — plausibly reflecting stronger students leaving the state — even though simply having taken the ACT at all is protective.</p>
<p><br></p>
</section>
<section id="disparities-compound-across-the-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="disparities-compound-across-the-pipeline">Disparities Compound Across the Pipeline</h3>
<p>The characteristics associated with <em>not completing college in the first place</em> deserve to be viewed alongside the disconnection risk factors above, because for some groups, disadvantage compounds at every stage of the pipeline rather than being confined to one point.</p>
<p><strong>American Indian and Hispanic graduates</strong> face the steepest barriers to completing a postsecondary credential at all, among the largest disparities found anywhere in this project. <strong>Economically disadvantaged graduates and special education students</strong> face substantial completion barriers as well — the two largest demographic gaps in the completion model — that shrink but do not disappear once high school accomplishments are controlled for. For these groups, disadvantage doesn’t resolve after high school; it shows up again, sometimes in a different form, at the completion stage and again in the workforce-attachment stage that follows.</p>
<p>Notably, <strong>Black graduates</strong> are the clearest example of a genuinely different pattern: no elevated barrier to completing college, but the single largest and most persistent disadvantage in regional workforce attachment among both completers and non-completers, and the largest disparity in persistent job instability specifically. Their disadvantage is not about <em>access</em> to postsecondary education — it shows up later, in the labor market itself.</p>
<p><br></p>
</section>
</section>
<section id="what-offers-protection-against-disconnection" class="level2">
<h2 class="anchored" data-anchor-id="what-offers-protection-against-disconnection">What Offers Protection Against Disconnection?</h2>
<section id="protections-against-persistent-instability" class="level3">
<h3 class="anchored" data-anchor-id="protections-against-persistent-instability">Protections Against Persistent Instability</h3>
<p>Relatively few levers meaningfully reduce the risk of persistent job instability once demographics and context are accounted for — this is, on the whole, a harder problem to intervene on through high-school-level programming alone. The clearest protective factors identified are:</p>
<ul>
<li><strong>Attempting postsecondary education, even without completing it</strong>, is the single strongest protective factor against job instability identified in this analysis — graduates who attended some postsecondary education show substantially lower odds of persistent instability than those who never attended.</li>
<li><strong>Coming from EDR 8</strong> is independently protective against job instability, even though it is a risk factor for the other form of disconnection (see below).</li>
<li>Notably, high school accomplishments that are powerful levers elsewhere in this project — CTE engagement, ACT participation, PSEO — show <strong>no significant protective effect against job instability specifically</strong> once other factors are controlled for. Their well-documented protective power throughout this project operates almost entirely through the second mechanism.</li>
</ul>
<p><br></p>
</section>
<section id="protections-against-persistent-no-mn-employment-record-status" class="level3">
<h3 class="anchored" data-anchor-id="protections-against-persistent-no-mn-employment-record-status">Protections Against Persistent No-MN-Employment-Record Status</h3>
<p>This is where the strongest, most numerous protective levers in the entire disconnection analysis are found — and it is where CTE, ACT engagement, and PSEO participation, all essentially inert against job instability, show their power.</p>
<ul>
<li><strong>CTE achievement level and total CTE courses taken</strong> are both large, independent protective factors — the single strongest protective levers identified anywhere in this project for keeping non-completers visible in Minnesota’s workforce data.</li>
<li><strong>Having taken the ACT</strong> is strongly protective — one of the largest protective effects found in this entire analysis — even though, among test-takers, a higher score on that same test is associated with elevated risk.</li>
<li><strong>PSEO participation</strong> is independently protective.</li>
<li><strong>Attempting postsecondary education without completing it</strong> is protective here as well, confirming it as the one lever in this entire non-completer analysis that helps with both forms of disconnection at once.</li>
<li><strong>Economic disadvantage and higher local unemployment</strong> are, somewhat counterintuitively, both associated with <em>lower</em> risk of disappearing from the workforce record — plausibly because economic constraint limits graduates’ ability to leave the local labor market or the state altogether, keeping them visible in Minnesota’s data even when the work available to them is limited.</li>
<li><strong>Coming from EDR 6E</strong>, and from a <strong>town/rural mix</strong> community background, are both independently protective.</li>
</ul>
<p>Taken together, these findings point to a clear, practical distinction for anyone designing an intervention: programs built around CTE, ACT engagement, or PSEO will meaningfully reduce the risk of graduates disappearing from Minnesota’s workforce entirely, but will do little to address job instability specifically. Programs aimed at job instability — which disproportionately affects women, special education students, and Black graduates — need a different toolkit; on this evidence, only sustained postsecondary engagement (even without completion) shows a clear, independent protective effect on that front.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>